-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN641', 'that_thguy', NULL, 'https://www.instagram.com/that_thguy/', 'instagram', 'micro', ARRAY['diecast', 'toys']::text[], 80000, 'hotwheels', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-cf061dc0149a485d'),
('IN642', 'gowri.karanth', NULL, 'https://www.instagram.com/gowri.karanth/', 'instagram', 'micro', ARRAY['cinematic', 'ugc', 'vlogs']::text[], 150000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ead64b2765697175'),
('IN643', 'zaynmarie', NULL, 'https://www.instagram.com/zaynmarie/', 'instagram', 'macro', ARRAY['ugc']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-11e136bd13019058'),
('IN644', 'unique_rohit14', NULL, 'https://www.instagram.com/unique_rohit14/', 'instagram', 'macro', ARRAY['finds', 'review', 'vlogs']::text[], 100000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-64e4bf1a4647ee15'),
('IN645', 'wholesalewala_pune', NULL, 'https://www.instagram.com/wholesalewala_pune/', 'instagram', 'micro', ARRAY['toys', 'diecast', 'finds']::text[], 20000, 'store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f924f6a58eaa51e4'),
('IN646', 'shanuuuz_fvz', NULL, 'https://www.instagram.com/shanuuuz_fvz/reels/', 'instagram', 'nano', ARRAY['vlogs', 'ugc', 'cinematic']::text[], 10000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-57d45a7000afd4e6'),
('IN647', 'ms_selection_jodhpur', NULL, 'https://www.instagram.com/ms_selection_jodhpur/', 'instagram', 'macro', ARRAY['finds', 'toys']::text[], 50000, 'store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-184ea1c9f868a595'),
('IN648', 'srbuniverse_', NULL, 'https://www.instagram.com/srbuniverse_/', 'instagram', 'macro', ARRAY['vlogs']::text[], 60000, 'travel', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-315dc9822c095001'),
('IN649', 'iam_kavipriya_', NULL, 'https://www.instagram.com/iam_kavipriya_/', 'instagram', 'macro', ARRAY['ugc', 'vlogs']::text[], 80000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0053698f5f88c9a7'),
('IN650', 'yogi.arts', NULL, 'https://www.instagram.com/yogi.arts/', 'instagram', 'macro', ARRAY['tech']::text[], 60000, 'tech content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5a75749e1f632d19'),
('IN651', 'nidh_iieeee', 'Nidhi Kesharwani', 'https://www.instagram.com/nidh_iieeee/reels/', 'instagram', 'nano', ARRAY['review', 'finds', 'unboxing']::text[], 20000, 'general finds', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ae8de26a12f0d33a'),
('IN652', 'digitalbabuoffl', 'Babu', 'https://www.instagram.com/digitalbabuoffl/reels/', 'instagram', 'micro', ARRAY['review', 'finds', 'toys']::text[], 100000, 'reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-747e59c91fb10c9e'),
('IN653', 'krishnanidhiplayhouse', 'Krishna Nidhi', 'https://www.instagram.com/krishnanidhiplayhouse/reels/', 'instagram', 'nano', ARRAY['vlogs', 'ugc']::text[], 7000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-71740fe2b526ae91'),
('IN654', 'crazysam.ig', NULL, 'https://www.instagram.com/crazysam.ig/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], 10000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5099aa27dd106a15'),
('IN655', 'anjalimanukamra', 'Anjali Mannu Kamra', 'https://www.instagram.com/anjalimanukamra/reels/', 'instagram', 'nano', ARRAY['finds', 'vlogs']::text[], 30000, 'product reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a7b6d464f82812ec'),
('IN656', 'topinternetfinds_india', NULL, 'https://www.instagram.com/topinternetfinds_india/reels/', 'instagram', 'micro', ARRAY['vlogs', 'finds', 'review', 'unboxing']::text[], 10000, 'general reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d8ebf2206340fccd'),
('IN657', 'gaur.aang', 'Gauraang Arora', 'https://www.instagram.com/gaur.aang/reels/', 'instagram', 'nano', ARRAY['tech', 'finds', 'review']::text[], 5000, 'tech', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6eff9dc099c38ee8'),
('IN658', 'startup_with_nikunj', 'Nikunj Sharma', 'https://www.instagram.com/startup_with_nikunj/reels/', 'instagram', 'nano', ARRAY['review', 'finds']::text[], 25000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9c9d5017f4d0487d'),
('IN659', 'viraj_ghelani', NULL, 'https://www.instagram.com/viraj_ghelani/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 2000000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a7912dffe8c81f51'),
('IN660', 'ezsnippet', NULL, 'https://www.instagram.com/ezsnippet/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 2000000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-67eb7bd5fa2533b7'),
('IN661', '_sketch_something_', NULL, 'https://www.instagram.com/_sketch_something_/reels/', 'instagram', 'macro', ARRAY['vlogs', 'review']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a0d33298ef183397'),
('IN662', 'macmacha', NULL, 'https://www.instagram.com/macmacha/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 200000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3c70e7d07464056d'),
('IN663', 'foodiebharathi', 'JEYA BHARATHI', 'https://www.instagram.com/foodiebharathi/reels/', 'instagram', 'macro', ARRAY['finds', 'review', 'vlogs']::text[], 300000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-2a26a770e982ab04'),
('IN664', 'dasoham_', NULL, 'https://www.instagram.com/dasoham_/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 1500000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0c77991d37e42898'),
('IN665', 'moonmayanyt', 'Mayank', 'https://www.instagram.com/moonmayanyt/reels/', 'instagram', 'nano', ARRAY['tech', 'finds']::text[], 20000, 'tech content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-504db73656f22629'),
('IN666', 'mozhiyin_mozhi', 'Mozhiyin Mozhi', 'https://www.instagram.com/mozhiyin_mozhi/reels/', 'instagram', 'micro', ARRAY['toys', 'vlogs', 'finds', 'review']::text[], 15000, 'mom blogger', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-899fcea43d147d3e'),
('IN667', 'artofgauri', 'Gauri Rajput', 'https://www.instagram.com/artofgauri/reels/', 'instagram', 'micro', ARRAY['toys', 'vlogs']::text[], 10000, 'art', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5ce8545b0b043c87'),
('IN668', 'aditya.tokare', 'Aditya Tokare', 'https://www.instagram.com/aditya.tokare/reels/', 'instagram', 'macro', ARRAY['tech', 'cinematic']::text[], 150000, 'tech reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0a4f34a1b6de0873'),
('IN669', 'hotwheels__hunt', NULL, 'https://www.instagram.com/hotwheels__hunt/reels/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], 5000, 'hotwheels', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0f3eb8d1d35e8d7d'),
('IN670', 'rennwagon.in', NULL, 'https://www.instagram.com/rennwagon.in/reels/', 'instagram', 'nano', ARRAY['diecast']::text[], 10000, 'hotwheels', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-75947e1662a6d7e5'),
('IN671', 'technolobe', 'Harsh Punjabi', 'https://www.instagram.com/technolobe/reels/', 'instagram', 'macro', ARRAY['tech', 'review']::text[], 150000, 'tech', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5b3835d598c4c4d9'),
('IN672', 'dannyypandit', 'Danny pandit', 'https://www.instagram.com/dannyypandit/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 3000000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e377a183dac78cbb'),
('IN673', 'explorewithsahil01', 'Sahil', 'https://www.instagram.com/explorewithsahil01/', 'instagram', 'micro', ARRAY['finds', 'cinematic', 'vlogs']::text[], 80000, 'general content', NULL, '+919004619851', '903 , 9th floor , b wing , vardhman empire , dominic colony road no 1 , orlem , Malad West, Mumbai -400064', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-24bcdf84c1bda9f3'),
('IN674', 'goodgujjju', 'Kaumil Gajera', 'https://www.instagram.com/goodgujjju/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c9e93f5699aa6acb'),
('IN675', 'my_minigarage_', NULL, 'https://www.instagram.com/my_minigarage_/reels/', 'instagram', 'nano', ARRAY['toys', 'diecast']::text[], 10000, 'diecast', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-191dc3b8f395b95f'),
('IN676', '_createyourtaste_', NULL, 'https://www.instagram.com/_createyourtaste_/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 2000000, 'diy content', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8a7d7d7f09100d9c'),
('IN677', 'ontheground.with.sai', 'Sai Sethu', 'https://www.instagram.com/ontheground.with.sai/reels/', 'instagram', 'macro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a1c045ee6ea4db3b'),
('IN678', 'rishiudapurkar', NULL, 'https://www.instagram.com/rishiudapurkar/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-edff92ea1dc22bef'),
('IN679', 'yuvraj.dua', 'Yuvraj Dua', 'https://www.instagram.com/yuvraj.dua/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ee1b3dfd06f2bc1a'),
('IN680', 'aryan_approves', NULL, 'https://www.instagram.com/aryan_approves/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e871be069836a7f5')
ON CONFLICT (influencer_code) DO NOTHING;
