-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN561', 'neo_fly01', NULL, 'https://www.instagram.com/neo_fly01/reels/', 'instagram', 'micro', ARRAY['cinematic', 'vlogs']::text[], 15000, 'drone content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1f25250b904f4643'),
('IN562', 'punjabrchobbies', NULL, 'https://www.instagram.com/punjabrchobbies/reels/', 'instagram', 'micro', ARRAY['rc', 'toys']::text[], 25000, 'rc car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f3d7584a55b6c175'),
('IN563', 'dukevijay_official', NULL, 'https://www.instagram.com/dukevijay_official/reels/', 'instagram', 'macro', ARRAY['finds', 'vlogs', 'cinematic']::text[], 150000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-00ac84d0f2d8f55b'),
('IN564', 'vlogswithsuhail', NULL, 'https://www.instagram.com/vlogswithsuhail/reels/', 'instagram', 'micro', ARRAY['vlogs', 'finds']::text[], 200000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-25c29ccd64a4141f'),
('IN565', 'vanakkam_chennai_', NULL, 'https://www.instagram.com/vanakkam_chennai_/reels/', 'instagram', 'macro', ARRAY['vlogs', 'finds']::text[], 300000, 'vlogs/general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-15050445519126ac'),
('IN566', '_abhijith_soman_', NULL, 'https://www.instagram.com/_abhijith_soman_/reels/', 'instagram', 'macro', ARRAY['ugc', 'finds']::text[], 30000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-48b13c4e66c97596'),
('IN567', 'toytopia_paravur', NULL, 'https://www.instagram.com/toytopia_paravur/reels/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'toys']::text[], 15000, 'toy store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-82ec7f4d2e7a9d30'),
('IN568', 'worldoframyaa', NULL, 'https://www.instagram.com/worldoframyaa/reels/', 'instagram', 'micro', ARRAY['review', 'toys', 'rc']::text[], 10000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-41658a37312052bd'),
('IN569', 'swthsree_duoss', NULL, 'https://www.instagram.com/swthsree_duoss/reels/', 'instagram', 'nano', ARRAY['ugc', 'vlogs']::text[], 20000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0bcf9e03b176dfda'),
('IN570', 'speedy.souls', NULL, 'https://www.instagram.com/speedy.souls/reels/', 'instagram', 'macro', NULL, 80000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-23744d401055e1c4'),
('IN571', 'littlesamagra0110', NULL, 'https://www.instagram.com/littlesamagra0110/reels/', 'instagram', 'macro', ARRAY['vlogs', 'finds']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-8a8eb5d93c239737'),
('IN572', 'jaiambeyenterprise', NULL, 'https://www.instagram.com/jaiambeyenterprise/reels/', 'instagram', 'micro', ARRAY['finds', 'unboxing']::text[], 5000, 'store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9d24574fdfd2f82c'),
('IN573', 'gamemart_', NULL, 'https://www.instagram.com/gamemart_/reels/', 'instagram', 'micro', ARRAY['toys', 'tech', 'finds']::text[], 30000, 'game store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ddcbdaaac8e9c09f'),
('IN574', 'broo_tech07', NULL, 'https://www.instagram.com/broo_tech07/reels/', 'instagram', 'micro', ARRAY['tech']::text[], 20000, 'tech content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d8f10d2b35a0317c'),
('IN575', 'petrol_hunter', NULL, 'https://www.instagram.com/petrol_hunter/reels/', 'instagram', 'macro', NULL, 200000, 'car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5ee7c478f7f99dfe'),
('IN576', 'playmastertoys123', NULL, 'https://www.instagram.com/playmastertoys123/reels/', 'instagram', 'nano', ARRAY['diecast', 'toys', 'rc']::text[], 5000, 'store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1006843350472496'),
('IN577', 'explorewith.dev', NULL, 'https://www.instagram.com/explorewith.dev/', 'instagram', 'micro', ARRAY['finds']::text[], 50000, 'food and travel', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-fce26685b77ac600'),
('IN578', 'harshhhgautam', NULL, 'https://www.instagram.com/harshhhgautam/', 'instagram', 'macro', ARRAY['tech', 'finds', 'vlogs']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-006e87944bf99d9f'),
('IN579', '_aruncreates__', NULL, 'https://www.instagram.com/_aruncreates__/', 'instagram', 'micro', NULL, 40000, 'general content/finance', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-4e44cda591ab2a2e'),
('IN580', 'chalibro', NULL, 'https://www.instagram.com/chalibro/', 'instagram', 'micro', ARRAY['vlogs']::text[], 1000000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5c1a5164ce8e1c49'),
('IN581', 'anindiantourist', NULL, 'https://www.instagram.com/anindiantourist/', 'instagram', 'micro', ARRAY['finds', 'cinematic']::text[], 50000, 'travel', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-562b39cc5c942e57'),
('IN582', 'lrlmotors_service', NULL, 'https://www.instagram.com/lrlmotors_service/', 'instagram', 'nano', ARRAY['finds', 'review']::text[], 3000, 'moto content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-7d80f928d877e23b'),
('IN583', 'unique_shopping_karaikudi', NULL, 'https://www.instagram.com/unique_shopping_karaikudi/', 'instagram', 'macro', ARRAY['toys', 'rc', 'tech', 'finds']::text[], 100000, 'store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a9cedcc3559e6456'),
('IN584', 'modified_garage_kerala', NULL, 'https://www.instagram.com/modified_garage_kerala/', 'instagram', 'micro', NULL, 5000, 'auto content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6735293ebeb395d2'),
('IN585', 'goldeyesight', NULL, 'https://www.instagram.com/goldeyesight/', 'instagram', 'micro', NULL, 250000, 'bike content', NULL, '+917303814326', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d53c1697b43789f2'),
('IN586', 'bharath_369_', NULL, 'https://www.instagram.com/bharath_369_/', 'instagram', 'micro', ARRAY['vlogs', 'finds']::text[], 50000, 'food/vlogs', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0105eb0ff24a4439'),
('IN587', 'urvishkaushik_', NULL, 'https://www.instagram.com/urvishkaushik_/', 'instagram', 'micro', NULL, 200000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-8964fa72de0fb762'),
('IN588', '_darshinigowda_', NULL, 'https://www.instagram.com/_darshinigowda_/', 'instagram', 'nano', ARRAY['ugc', 'finds']::text[], 60000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-52f0f023400c058a'),
('IN589', 'yashrajchaudhary09', NULL, 'https://www.instagram.com/yashrajchaudhary09/', 'instagram', 'nano', ARRAY['vlogs']::text[], 10000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5d641dc6f4a6651c'),
('IN590', 'me.bonie', NULL, 'https://www.instagram.com/me.bonie/', 'instagram', 'micro', NULL, 50000, 'car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-44acd38cb67f5371'),
('IN591', 'ashu.ghai', NULL, 'https://www.instagram.com/ashu.ghai/', 'instagram', 'macro', ARRAY['review', 'finds']::text[], 2000000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-71b31680cb80ba2b'),
('IN592', 'all.about.azeem', NULL, 'https://www.instagram.com/all.about.azeem/', 'instagram', 'micro', ARRAY['finds', 'vlogs']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-833026f9312fcb64'),
('IN593', 'kanishyamo', NULL, 'https://www.instagram.com/kanishyamo/', 'instagram', 'micro', ARRAY['ugc', 'finds', 'vlogs']::text[], 15000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ca79653a3a6244f0'),
('IN594', 'chanchal__gahlawat', NULL, 'https://www.instagram.com/chanchal__gahlawat/', 'instagram', 'macro', ARRAY['vlogs', 'ugc']::text[], 70000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b5b8c82c5b9b24b1'),
('IN595', 'weekendplansorted', NULL, 'https://www.instagram.com/weekendplansorted/', 'instagram', 'micro', ARRAY['finds', 'cinematic']::text[], 20000, 'travel/lifstyle', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b7559994e5394733'),
('IN596', 'petta_rap', NULL, 'https://www.instagram.com/petta_rap/', 'instagram', 'macro', ARRAY['finds', 'review']::text[], 5000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-fc77c058538019fa'),
('IN597', 'riachops', NULL, 'https://www.instagram.com/riachops/', 'instagram', 'micro', ARRAY['vlogs']::text[], 30000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-aac6cc0a48ac18bc'),
('IN598', '_roopaul_', NULL, 'https://www.instagram.com/_roopaul_/', 'instagram', 'macro', ARRAY['vlogs', 'finds']::text[], 100000, 'fashion/vlogs', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-839217e0a215b457'),
('IN599', 'lookwhostalking_', NULL, 'https://www.instagram.com/lookwhostalking_/', 'instagram', 'nano', NULL, 2000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f6e0d3b50207ea08'),
('IN600', 'petrichor_graphix', NULL, 'https://www.instagram.com/petrichor_graphix/', 'instagram', 'micro', ARRAY['finds', 'vlogs']::text[], 5000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-2dc7b078be32ed75')
ON CONFLICT (influencer_code) DO NOTHING;
