-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN321', 'myma_kidsstore', NULL, 'https://www.instagram.com/myma_kidsstore/', 'instagram', 'nano', ARRAY['rc', 'toys', 'review', 'unboxing']::text[], 2000, 'kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-478d3a06f4372a15'),
('IN322', 'kochimachan', NULL, 'https://www.instagram.com/kochimachan/', 'instagram', 'macro', ARRAY['tech', 'vlogs', 'diecast', 'unboxing']::text[], 70000, 'Enthusiasts', 'Kochi/Kerala', '+918089336889', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c3761601c6bdcbf1'),
('IN323', 'palakkadann_kazhchakal', NULL, 'https://www.instagram.com/palakkadann_kazhchakal/', 'instagram', 'nano', ARRAY['vlogs', 'diecast', 'review']::text[], 80000, 'general', 'palakkad', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a73dae6d0b2f9326'),
('IN324', 'punyalanentertainment', 'George Punyalan', 'https://www.youtube.com/@punyalanentertainment', 'youtube', 'nano', ARRAY['vlogs', 'diecast', 'unboxing']::text[], 7500, 'Enthusiasts/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7a3cda9a736c0069'),
('IN325', 'santra.immanuvel', 'Santra', 'https://www.instagram.com/santra.immanuvel/', 'instagram', 'nano', ARRAY['vlogs', 'diecast']::text[], 50000, 'general/enthusiasts', 'Coimbatore', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2ec5ef0782124177'),
('IN326', 'tokozhikode', NULL, 'https://www.instagram.com/tokozhikode/', 'instagram', 'macro', ARRAY['finds', 'diecast', 'tech', 'vlogs']::text[], 150000, 'general', 'Kozhikode', '+918089644396', 'Sajith Sivanandan Makkolath Meethal Po Medical College Kozhikode -8 Pincode 673008', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f31c660e781182ca'),
('IN327', 'kovaifoodvlog', 'Vikash', 'https://www.instagram.com/kovaifoodvlog/', 'instagram', 'micro', ARRAY['diecast', 'vlogs']::text[], 30000, 'general/enthusiasts', 'Coimbatore', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-59827c91a38e00f5'),
('IN328', 'minimarvels.shop', NULL, 'https://www.instagram.com/minimarvels.shop/', 'instagram', 'nano', ARRAY['diecast']::text[], 15000, 'Enthusiasts', 'Kerala', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-146684d3db058d0e'),
('IN329', 'abbaonlineshoppe', NULL, 'https://www.instagram.com/abbaonlineshoppe/', 'instagram', 'nano', ARRAY['review', 'diecast', 'rc', 'cinematic']::text[], 7000, 'Enthusiasts', 'Kerala', '+917907542434', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-bc28138c14e70135'),
('IN330', 'onlinesesastastore', NULL, 'https://www.instagram.com/onlinesesastastore/', 'instagram', 'nano', ARRAY['review', 'rc', 'toys', 'diecast']::text[], 9000, 'kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-58fb60e47f24db33'),
('IN331', 'faheem.toyland', NULL, 'https://www.instagram.com/faheem.toyland/', 'instagram', 'nano', ARRAY['toys', 'rc', 'diecast']::text[], 4500, 'Kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c54338313477afa3'),
('IN332', 'bharath_135_', 'Bharath', 'https://www.instagram.com/bharath_135_/', 'instagram', 'macro', ARRAY['vlogs']::text[], 300000, 'general', 'Kollam', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-343a49211e83e025'),
('IN333', 'bharathvijayan_', 'Bharath', 'https://www.instagram.com/bharathvijayan_/', 'instagram', 'nano', ARRAY['vlogs', 'diecast']::text[], 45000, 'General', 'Kollam', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3361cffd584fbe5a'),
('IN334', 'trivian_crazy_vlogger', 'Arun S. R.', 'https://www.instagram.com/trivian_crazy_vlogger/', 'instagram', 'micro', ARRAY['vlogs', 'diecast', 'review']::text[], 50000, 'general', 'Trivandrum', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-eb9860679075fa4b'),
('IN335', 'hungry4fooding', 'Sree Hari JH', 'https://www.instagram.com/hungry4fooding/', 'instagram', 'nano', ARRAY['diecast', 'vlogs']::text[], 60000, 'General', 'Kerala', '+918590214078', 'AGRA 31 Priya Bhavan Aiswarya  Gardens Near Petrol Pump Peroorkkada 695005', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-bbdd31f69e22eff9'),
('IN336', 'jdbt_toy_store', NULL, 'https://www.instagram.com/jdbt_toy_store/', 'instagram', 'macro', ARRAY['diecast', 'toys', 'rc', 'review', 'unboxing']::text[], 100000, 'Kids/Enthusiasts', NULL, '+919677251204', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-82409d394b1c965a'),
('IN337', 'rohit_paradkar', 'Rohit Paradkar', 'https://www.instagram.com/rohit_paradkar/', 'instagram', 'micro', ARRAY['diecast', 'rc', 'auto', 'review', 'unboxing']::text[], 25000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d19c93cd265e036e'),
('IN338', 'abuz_collections', NULL, 'https://www.instagram.com/abuz_collections?igsh=MWl0eG5saXJoOWg5bQ==', 'instagram', 'nano', ARRAY['rc', 'toys', 'tech']::text[], 2500, 'kids/general', NULL, '+917397332904', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-5592038665ab1ed7'),
('IN339', 'toysvillaindia', NULL, 'https://www.instagram.com/toysvillaindia?igsh=MXVkZ2NrcmE5NWF2eg==', 'instagram', 'micro', ARRAY['toys', 'diecast', 'rc']::text[], 100000, 'kids/enthusiasts', 'Vadodara', '+919875001944', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7cdf511129b3286a'),
('IN340', 'automodelleindia', NULL, 'https://www.instagram.com/automodelleindia?igsh=M3I2czlhano5anNs', 'instagram', 'micro', ARRAY['diecast', 'toys', 'review', 'unboxing']::text[], 5000, 'kids/enthusiasts', 'Kochi', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ec0604be1bf0e661'),
('IN341', 'coolbabytoys', NULL, 'https://www.instagram.com/coolbabytoys?igsh=MTBnMmpieGNveml5Mg==', 'instagram', 'nano', ARRAY['diecast', 'rc', 'toys']::text[], 30000, 'kids/enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-408fed09a8140ffd'),
('IN342', 'art_and_travel_with_rahul', 'Rahul Ramachandran', 'https://www.instagram.com/art_and_travel_with_rahul?igsh=MTZ6cjljNHZ1em0xNw==', 'instagram', 'nano', ARRAY['tech', 'vlogs', 'auto', 'rc']::text[], 10000, 'enthusiasts', NULL, NULL, NULL, 'rahullalu501@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-fa2365284321bdbf'),
('IN343', 'byg_products_', NULL, 'https://www.instagram.com/byg_products_?igsh=MXg3MDZhZnpmdWVs', 'instagram', 'nano', ARRAY['diecast', 'unboxing', 'review']::text[], 20000, 'enthusiasts', 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c86b89af1d75cf0a'),
('IN344', 'travelwithsparks', NULL, 'https://www.instagram.com/travelwithsparks?igsh=MTl5NTU0dGx3anhwbw==', 'instagram', 'nano', ARRAY['vlogs', 'tech', 'diecast', 'finds']::text[], 50000, 'general', NULL, '+919080777208', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1e0627bb81f80eb8'),
('IN345', 'anjanaautomotives', NULL, 'https://www.instagram.com/anjanaautomotives?igsh=MTYxZ2V0N29lc25uMg==', 'instagram', 'nano', ARRAY['diecast', 'review']::text[], 2500, 'enthusiasts', 'Chennai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-eaf3f50a43171bc3'),
('IN346', 'indisojodhpur', NULL, 'https://www.instagram.com/indisojodhpur?igsh=MTdzOTQ5aWpheTB2NA==', 'instagram', 'nano', ARRAY['toys', 'rc', 'diecast', 'review']::text[], 12000, 'kids/enthusiasts', 'Jodhpur', '+917568686078', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4eca95346b8ff07c'),
('IN347', 'nandishbansi', 'Nandish Bansi', 'https://www.instagram.com/nandishbansi?igsh=ZGNxcGt3MnczdnBk', 'instagram', 'nano', ARRAY['diecast', 'review']::text[], 1000, 'enthusiasts/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-780552fc1581b1b2'),
('IN348', 'kidonex.official', NULL, 'https://www.instagram.com/kidonex.official/', 'instagram', 'nano', ARRAY['toys', 'diecast', 'rc']::text[], 10000, 'kids/Parents', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-96ac6ea307f1e2f9'),
('IN349', 'travel_tech_food_by_promodbabu', 'Promod Babu', 'https://www.facebook.com/promodbabutdpa?mibextid=ZbWKwL#', 'other', 'macro', ARRAY['diecast', 'tech', 'review', 'vlogs']::text[], 28000, 'general', 'Thodupuzha', '+919961874959', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0ac47f5ec0894728'),
('IN350', 'stories_of_thodupuzha', NULL, 'https://www.instagram.com/stories_of_thodupuzha/', 'instagram', 'nano', ARRAY['vlogs']::text[], 10000, 'general', 'Thodupuzha', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1421f42e260fc794'),
('IN351', 'jaimantoys', NULL, 'https://www.instagram.com/jaimantoys/', 'instagram', 'nano', ARRAY['toys', 'diecast', 'rc']::text[], 1500, 'kids/enthusiasts', 'New Delhi', '+919899747688', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4a5277d72fee7c9c'),
('IN352', 'miniatures_collectable', NULL, 'https://www.instagram.com/miniatures_collectable/', 'instagram', 'nano', ARRAY['unboxing', 'diecast', 'toys']::text[], 5000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-5a6a48497bdabc4e'),
('IN353', 'vijay_vox.in', 'Vijay', 'https://www.instagram.com/vijay_vox.in/reels/', 'instagram', 'nano', ARRAY['unboxing', 'review', 'tech', 'toys', 'diecast']::text[], 10000, 'enthusiasts', NULL, '+917448503605', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f1c82257d20c63a9'),
('IN354', 'dream_anime.retail', NULL, 'https://www.instagram.com/dream_anime.retail/reels/', 'instagram', 'nano', ARRAY['diecast', 'toys', 'review', 'unboxing']::text[], 15000, 'enthusiasts', 'Balasore', '+917377179947', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-531ebd1290e51279'),
('IN355', 'explorewith.dev', 'Dev Patel', 'https://www.instagram.com/explorewith.dev/reels/', 'instagram', 'micro', ARRAY['vlogs', 'diecast', 'review', 'finds']::text[], 30000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8d9680b5ead6724b'),
('IN356', 'j.m.t_store', NULL, 'https://www.instagram.com/j.m.t_store/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'toys', 'tech']::text[], 2000, 'enthusiasts', 'TamilNadu', '+918903659496', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1942a684ae12a3b5'),
('IN357', 'karthikeyan_stores', NULL, 'https://www.instagram.com/karthikeyan_stores/', 'instagram', 'nano', ARRAY['rc', 'unboxing', 'review', 'diecast']::text[], 4500, 'enthusiasts', 'Coimbatore', '+918778112724', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0f0e6c1b9e41df47'),
('IN358', 'g_talks_orginals', NULL, 'https://www.instagram.com/g_talks_orginals/', 'instagram', 'nano', ARRAY['vlogs']::text[], 9000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d728049652b0dbe0'),
('IN359', 'the_road_burner__', 'Amal', 'https://www.instagram.com/the_road_burner__/reels/', 'instagram', 'nano', ARRAY['vlogs', 'diecast']::text[], 9500, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-17b33f3485c6b74c'),
('IN360', 'moments_gifts_shop', NULL, 'https://www.instagram.com/moments_gifts_shop/', 'instagram', 'nano', ARRAY['toys', 'diecast', 'review', 'rc']::text[], 15000, 'enthusiasts/gifts', 'Muvattupuzha', '+918075406801', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a4abebe05641fc17')
ON CONFLICT (influencer_code) DO NOTHING;
