-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN1084', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cb899954ce2a3f21'),
('IN1085', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-190151adc3406366'),
('IN1086', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-65eb60da3c1fe752'),
('IN1087', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4ccf82da1b2b83ae'),
('IN1088', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-90f2ef760719f2c5'),
('IN1089', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4d6f18afdf806ee3'),
('IN1090', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-aeb768efcea8101d'),
('IN1091', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-662f1002bead6936'),
('IN1092', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9c73588735102b34'),
('IN1093', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-50307f936790345a'),
('IN1094', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7f348001f4ff90fb'),
('IN1095', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ebc853c74665596c'),
('IN1096', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7670120586245306'),
('IN1097', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e3ecb88fc16e2aac'),
('IN1098', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-946c2cd0f24ab531'),
('IN1099', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e9d50a1f24052575'),
('IN1100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8b1ef290ddde5bc8'),
('IN1101', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-da5f5523d3fecf62'),
('IN1102', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-29aa9cdb811374a7'),
('IN1103', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a8470268449578ef'),
('IN1104', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-83bf5b1068316cb0'),
('IN1105', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c4a4bf7fa9444b8b'),
('IN1106', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-5205ec0855850001'),
('IN1107', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a306fd5f00d30ff8'),
('IN1108', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c77e5b9c415d1279'),
('IN1109', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-38971bd3a97f6edd'),
('IN1110', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f5f13f9e32996f1a'),
('IN1111', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3c70cb35d298163e'),
('IN1112', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-01ac87d2001c4ab0'),
('IN1113', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1b4c6e7e69a786dd'),
('IN1114', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-80ea4390e86558c0'),
('IN1115', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a6429549d5508a90'),
('IN1116', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d98a87cbe9dfb028'),
('IN1117', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-72c2f9a7a0bad9fc'),
('IN1118', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-02b52a54db39e188'),
('IN1119', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e9f093545408333b'),
('IN1120', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-948bc48fc3c8e901'),
('IN1121', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9768a297177a49bc'),
('IN1122', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-01309eb03b320f63'),
('IN1123', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-fd0b9285c599b387')
ON CONFLICT (influencer_code) DO NOTHING;
