-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN601', 'thereviewingfamilyy', NULL, 'https://www.instagram.com/thereviewingfamilyy/reels/', 'instagram', 'nano', ARRAY['review', 'finds', 'vlogs']::text[], 15000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a4c666ac0ddcd1c9'),
('IN602', 'gaming_fun_army_21', NULL, 'https://www.instagram.com/gaming_fun_army_21/reels/', 'instagram', 'micro', ARRAY['finds', 'review', 'unboxing', 'tech', 'toys']::text[], 50000, 'finds/reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ca470fe3f70e8a13'),
('IN603', 'vampfyre1', NULL, 'https://www.instagram.com/vampfyre1/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 150000, 'gaming content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0da15621184818a5'),
('IN604', 'lakshaychaudhari', NULL, 'https://www.instagram.com/lakshaychaudhari/reels/', 'instagram', 'micro', ARRAY['review', 'finds']::text[], 200000, 'product suggestion', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e81c36e7ae30dbd2'),
('IN605', 'gaurav_uncut', NULL, 'https://www.instagram.com/gaurav_uncut/reels/', 'instagram', 'micro', ARRAY['cinematic']::text[], 10000, 'photography', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5245c72aacda5eb3'),
('IN606', 'shashwattt', NULL, 'https://www.instagram.com/shashwattt/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 150000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-83b949011aa7eb21'),
('IN607', 'kh_playsonic', NULL, 'https://www.instagram.com/kh_playsonic/reels/', 'instagram', 'micro', ARRAY['toys', 'tech']::text[], 20000, 'reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-8c4bfffc3f9c9395'),
('IN608', 'azlanshahofficial', NULL, 'https://www.instagram.com/azlanshahofficial/reels/', 'instagram', 'macro', ARRAY['vlogs', 'finds']::text[], 300000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0d9eea4d16963356'),
('IN609', 'oyenitin.official', NULL, 'https://www.instagram.com/oyenitin.official/reels/', 'instagram', 'micro', ARRAY['vlogs', 'ugc', 'review']::text[], 30000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b5d767b21cf263fe'),
('IN610', 'vijay3guy', NULL, 'https://www.instagram.com/vijay3guy/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 10000000, 'comedy', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c65e7befd29c2ac4'),
('IN611', 'kamalpahari_official', NULL, 'https://www.instagram.com/kamalpahari_official/reels/', 'instagram', 'micro', ARRAY['cinematic']::text[], 10000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f5eba919bbf677f1'),
('IN612', '_sneehhhaaa_', NULL, 'https://www.instagram.com/_sneehhhaaa_/', 'instagram', 'nano', ARRAY['ugc']::text[], 7000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-06305f169f1ee4db'),
('IN613', 'niharika_kabra', NULL, 'https://www.instagram.com/niharika_kabra/', 'instagram', 'micro', ARRAY['ugc']::text[], 60000, 'fashion/general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-bf88723fc85b0279'),
('IN614', 'techsupreme_', NULL, 'https://www.instagram.com/techsupreme_/', 'instagram', 'macro', ARRAY['tech']::text[], 150000, 'reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e8b17f42944a3b2d'),
('IN615', 'arpita.stories', NULL, 'https://www.instagram.com/arpita.stories/', 'instagram', 'nano', ARRAY['vlogs']::text[], 5000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3468001618564d13'),
('IN616', 'jass_creative', NULL, 'https://www.instagram.com/jass_creative/', 'instagram', 'nano', ARRAY['cinematic', 'vlogs']::text[], 3000, 'photography', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-451cc915febbc9cb'),
('IN617', 'pitlane.stories', NULL, 'https://www.instagram.com/pitlane.stories/', 'instagram', 'nano', NULL, 15000, 'f1 content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5fd8a2f8f187aaa2'),
('IN618', 'touhidahmadsocial', NULL, 'https://www.instagram.com/touhidahmadsocial/', 'instagram', 'nano', ARRAY['vlogs']::text[], 5000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0e19af183f57dff4'),
('IN619', 'hangstore.official', NULL, 'https://www.instagram.com/hangstore.official/', 'instagram', 'nano', ARRAY['finds', 'diecast']::text[], 7000, 'car decor', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-aaf9a601822072f3'),
('IN620', 'realtgfilms', NULL, 'https://www.instagram.com/realtgfilms/', 'instagram', 'micro', ARRAY['review', 'finds', 'tech']::text[], 450000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ceaeef12dad30c0e'),
('IN621', 'hungry_mannnn', NULL, 'https://www.instagram.com/hungry_mannnn/', 'instagram', 'micro', ARRAY['finds', 'vlogs']::text[], 50000, 'travel/lifestyle', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6ef5f2dffaa13015'),
('IN622', 'iamsharmiladasgupta', NULL, 'https://www.instagram.com/iamsharmiladasgupta/', 'instagram', 'nano', ARRAY['finds', 'ugc']::text[], 15000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ac42031f449d26ed'),
('IN623', 'mohan_jayanna', NULL, 'https://www.instagram.com/mohan_jayanna/', 'instagram', 'nano', NULL, 70000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-33be240e706de5f8'),
('IN624', 'vaishnaviip', NULL, 'https://www.instagram.com/vaishnaviip/', 'instagram', 'micro', NULL, 50000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9d6634759b9a0bde'),
('IN625', 'resh_maah__', NULL, 'https://www.instagram.com/resh_maah__/', 'instagram', 'micro', ARRAY['ugc']::text[], 40000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-cf0c9563b8d64ebf'),
('IN626', 'rahulbansaledits', NULL, 'https://www.instagram.com/rahulbansaledits/', 'instagram', 'macro', ARRAY['finds', 'review']::text[], 12000, 'editing content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1d9ae2437de0548b'),
('IN627', 'driftkingshop', NULL, 'https://www.instagram.com/driftkingshop/', 'instagram', 'macro', ARRAY['toys', 'diecast', 'rc']::text[], 25000, 'rc content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-50809fe25c6d1361'),
('IN628', 'krishnapadhi_', NULL, 'https://www.instagram.com/krishnapadhi_/', 'instagram', 'micro', ARRAY['ugc']::text[], 20000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c46b8e4d450c3747'),
('IN629', 'amalmukund_motospec', NULL, 'https://www.instagram.com/amalmukund_motospec/', 'instagram', 'nano', NULL, 10000, 'car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a407a023d18aefed'),
('IN630', 'techsanku', NULL, 'https://www.instagram.com/techsanku/', 'instagram', 'macro', ARRAY['review', 'tech']::text[], 150000, 'tech content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5915e944e44e1e69'),
('IN631', 'poojay____', NULL, 'https://www.instagram.com/poojay____/', 'instagram', 'nano', ARRAY['ugc']::text[], 5000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d1375ae5f26fc23c'),
('IN632', 'rajath_kk', NULL, 'https://www.instagram.com/rajath_kk/', 'instagram', 'nano', NULL, 50000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0c343aa6d84f1213'),
('IN633', 'laibakhanlodhi101', NULL, 'https://www.instagram.com/laibakhanlodhi101/', 'instagram', 'macro', NULL, 400000, 'car/auto content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c0e56d135b261e48'),
('IN634', 'darpansarvan_store', NULL, 'https://www.instagram.com/darpansarvan_store/', 'instagram', 'macro', NULL, 50000, 'store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6aa4900a7bcb0951'),
('IN635', 'tabz_nadeem', NULL, 'https://www.instagram.com/tabz_nadeem/', 'instagram', 'nano', ARRAY['finds', 'review', 'vlogs']::text[], 6000, 'fashion/store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1cfa7e2f368e8b1f'),
('IN636', 'simranchoudhary_official', NULL, 'https://www.instagram.com/simranchoudhary_official/', 'instagram', 'macro', ARRAY['ugc', 'review', 'vlogs']::text[], 150000, 'lifestyle', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-60c12770fa896a0e'),
('IN637', 'love.bite.explore', NULL, 'https://www.instagram.com/love.bite.explore/', 'instagram', 'micro', ARRAY['finds', 'review']::text[], 45000, 'food/reviews/finds', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-af41c07401d09063'),
('IN638', 'thechumbakstory', NULL, 'https://www.instagram.com/thechumbakstory/reels/', 'instagram', 'micro', ARRAY['vlogs', 'finds']::text[], 11000, 'random content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3673c5d03d01f705'),
('IN639', 'galanggjr_', NULL, 'https://www.instagram.com/galanggjr_/', 'instagram', 'macro', ARRAY['cinematic']::text[], 200000, 'photography', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b3ba118cf55cf7fb'),
('IN640', 'jananivisalakshi', NULL, 'https://www.instagram.com/jananivisalakshi/', 'instagram', 'macro', ARRAY['vlogs']::text[], 900000, 'fashion', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-408f3102c10fcb47')
ON CONFLICT (influencer_code) DO NOTHING;
