-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN201', 'chad_motos', NULL, '(4) Instagram', 'instagram', 'nano', ARRAY['unboxing', 'ugc', 'cinematic']::text[], 10000, 'Enthusiasts', 'Bangalore', '+919620345654', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-7e27bbeae8932c93'),
('IN202', 'rc_boy_telugu', NULL, '(3) Instagram', 'instagram', 'micro', ARRAY['rc', 'diecast']::text[], 100000, 'Enthusiasts', 'Telagana', '+916304729371', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-8442da97b28c33f6'),
('IN203', 'mylittleworld_2023', NULL, '(2) Instagram', 'instagram', 'nano', ARRAY['unboxing', 'ugc']::text[], 20000, 'Parens/ Kids', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-84e48dc8b5d74b36'),
('IN204', 'cs_videoguru', 'Pushpendra sharma', '(2) Instagram', 'instagram', 'micro', ARRAY['review']::text[], 20000, 'General', NULL, '+916394949831', 'No.121, Gokulpuri, near mela maidan in front of powerhouse lakhimpur kheri Uttar Pradesh 262701 plus code XQ5F+JF7', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-892d574005ea4dcf'),
('IN205', 'damivlogz', NULL, '(8) Instagram', 'instagram', 'micro', ARRAY['review', 'rc', 'diecast']::text[], 20000, 'Enthusiasts', NULL, '+916379215441', 'Vadugappatti Mettukkadu, Konganapuram, Salem - 637102 India', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-7198a6e362a0ea5e'),
('IN206', 'the_bikerdoc', NULL, '(9) Instagram', 'instagram', 'macro', ARRAY['review']::text[], 50000, 'Enthusiasts', NULL, '+918630661891', NULL, 'yourbikerdoc@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d629dc2c9fa90981'),
('IN207', 'the.binge.boy', NULL, '(3) Instagram', 'instagram', 'micro', ARRAY['review']::text[], 15000, 'General', NULL, '+918250585885', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1d63992ad5680048'),
('IN208', 'MiniatureAutomobiles', 'Nishchay Sharma', 'https://www.youtube.com/@MiniatureAutomobiles', 'youtube', 'brand', ARRAY['review', 'finds', 'cinematic', 'diecast']::text[], 50000, 'Enthusiasts', NULL, NULL, NULL, 'nisfbruno@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-ce8e1e27544dbb00'),
('IN209', 'diecastindia', NULL, 'https://www.instagram.com/diecastindia?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'nano', ARRAY['diecast', 'finds', 'review']::text[], 150000, 'Enthusiasts', NULL, '+919313490446', NULL, 'toysindia88@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-a1dc2992abee6048'),
('IN210', 'diecast._collector_', NULL, 'https://www.instagram.com/diecast._collector_?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'nano', ARRAY['review', 'finds', 'diecast']::text[], 10000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-25d0f80179e6f9e3'),
('IN211', 'ravikirankasturi', 'ravikiran kasturi', 'https://www.youtube.com/ravikirankasturi', 'youtube', 'nano', ARRAY['diecast', 'review']::text[], 12000, 'Enthusiasts', NULL, NULL, NULL, 'kasturi.ravikiran22@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-71752985af7cefb3'),
('IN212', 'keraladiecastcrew', 'Sankar Shaji', 'https://www.instagram.com/keraladiecastcrew/', 'instagram', 'nano', ARRAY['unboxing', 'review', 'diecast']::text[], 5000, 'Enthusiasts', 'Kerala', '+919847322279', '1/1992, Rajashree, Hilltop lane, Kumarapuram,Trivandrum - 695011', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-8fa9a20b20d18fe0'),
('IN213', 'hotwheelsshopindia', NULL, 'https://www.instagram.com/hotwheelsshopindia?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'nano', ARRAY['diecast']::text[], NULL, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b23423324a733c45'),
('IN214', 'scaleartsindia', NULL, 'https://www.instagram.com/scaleartsindia?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'nano', ARRAY['diecast', 'cinematic', 'review']::text[], 1500, 'Enthusiasts', 'Maharshtra', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2b52ed732d924018'),
('IN215', 'thedscollection', NULL, 'https://www.instagram.com/thedscollection?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'micro', ARRAY['diecast', 'unboxing', 'review']::text[], 50000, 'Enthusiasts', NULL, '+917004617192', NULL, 'diecasts@icloud.com', NULL, NULL, NULL, 'master', 'omnipres-inf-a6560587fe3de815'),
('IN216', 'toyznsargamm', NULL, 'https://www.instagram.com/toyznsargamm/', 'instagram', 'nano', ARRAY['toys', 'diecast']::text[], 10000, 'Enthusiasts', 'Gurugram', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2ae9eeec1a4c738a'),
('IN217', 'karz_and_dolls', NULL, 'https://www.instagram.com/karz_and_dolls/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], 10000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3844cbfcc1f17aa7'),
('IN218', 'thepeppystore.in', NULL, 'https://www.instagram.com/thepeppystore.in?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'micro', ARRAY['diecast', 'toys', 'unboxing', 'review']::text[], 10000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-351f4e31dd22cdbb'),
('IN219', 'rollingmetal_collectibles', NULL, 'https://www.instagram.com/rollingmetal_collectibles?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'nano', ARRAY['diecast']::text[], 4000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3ab46f3d96549ae7'),
('IN220', 'variety_metalcar_tvm_statue', NULL, 'https://www.instagram.com/variety_metalcar_tvm_statue?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'instagram', 'nano', ARRAY['diecast', 'cinematic']::text[], 50000, 'Enthusiasts', 'trivandrum', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6e49e9b47949d3dd'),
('IN221', 'kinderlogs', NULL, 'https://www.instagram.com/kinderlogs/', 'instagram', 'nano', ARRAY['diecast']::text[], 5000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7cd49285ce9c8ab0'),
('IN222', 'saikrishnastores', NULL, 'https://www.instagram.com/saikrishnastores/', 'instagram', 'macro', ARRAY['diecast', 'toys', 'rc']::text[], 180000, 'Enthusiasts', 'Chennai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-dbfb590dea9f2fe2'),
('IN223', 'customclans', NULL, 'https://www.instagram.com/customclans/', 'instagram', 'macro', ARRAY['rc', 'toys']::text[], 30000, 'Enthusiasts/kids', 'Nagpur', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6fb854e3c2954949'),
('IN224', 'rrm_motor_hub', NULL, 'https://www.instagram.com/rrm_motor_hub/reels/', 'instagram', 'micro', ARRAY['diecast', 'rc']::text[], 12000, 'Enthusiasts', NULL, NULL, NULL, 'ranbir_mehra@hotmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-da148e74c5b735a7'),
('IN225', 'best_home_.gadgets', 'Paridhi singh', 'https://www.instagram.com/best_home_.gadgets/', 'instagram', 'nano', ARRAY['finds', 'rc', 'unboxing', 'ugc']::text[], 6000, 'General', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-edd77aa8321f0933'),
('IN226', 'diecast_enthusiast__', 'Kannan', 'https://www.instagram.com/diecast_enthusiast__/', 'instagram', 'nano', ARRAY['diecast']::text[], 50000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-90aa7b4159763d16'),
('IN227', 'diecast_lunatic', 'Aswanth', 'https://www.instagram.com/diecast_lunatic/', 'instagram', 'nano', ARRAY['diecast', 'cinematic', 'unboxing']::text[], 15000, 'Enthusiasts', 'Kerala', '+96455692349961112112', 'Address: vazhinadakal (house), po vadanapplly, kizhake tippu supthan road, near sk flat. City : Vadanapplly. District: Thrissur. Pincode: 680614', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5f53d4a107fc2741'),
('IN228', 'the_mannat_store_india', NULL, 'https://www.instagram.com/the_mannat_store_india/', 'instagram', 'nano', ARRAY['toys', 'diecast']::text[], 10000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6dde65b837fc9d3b'),
('IN229', 'fancythings_india', NULL, 'https://www.instagram.com/fancythings_india/reels/', 'instagram', 'micro', ARRAY['diecast', 'unboxing']::text[], 25000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-52232b2d91033b5a'),
('IN230', 'thecomicbookstore.in', NULL, 'https://www.instagram.com/thecomicbookstore.in/', 'instagram', 'nano', ARRAY['diecast']::text[], 3000, 'Enthusiasts', 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cbda8fe4935b49f3'),
('IN231', 'abhishekbenny1', 'Abhishek Benny', 'https://www.instagram.com/abhishekbenny1/', 'instagram', 'nano', ARRAY['unboxing', 'diecast', 'rc', 'review']::text[], 50000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d99b2f404c8251f8'),
('IN232', 'snooplay.in', NULL, 'https://www.instagram.com/snooplay.in/', 'instagram', 'micro', ARRAY['toys', 'diecast', 'rc']::text[], 7500, 'General/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3ff16f7f27468ae2'),
('IN233', 'dhanaminiatures', NULL, 'https://www.instagram.com/dhanaminiatures', 'instagram', 'nano', ARRAY['tech', 'rc']::text[], 20000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1e622f45f3f0c461'),
('IN234', 'vijay_ideas', 'Vijay S', 'https://www.instagram.com/vijay_ideas/reels/', 'instagram', 'micro', ARRAY['finds', 'review', 'unboxing']::text[], 300000, 'general', 'Tamilnadu', '+916381732243', '172, Nadar Pillaiyar Kovil Street, Sivakasi, Near Kalaimagal School, Thiruthangal - 626130. Virudhunagar District. Tamilnadu', 'vijayideas.contact@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a77cd9630b44f367'),
('IN235', 'vcstoys', NULL, 'https://www.instagram.com/vcstoys/', 'instagram', 'nano', ARRAY['toys']::text[], 20000, 'Enthusiasts', NULL, '+96452617638921440456', 'VIMAL CS Sales manager Vcs toys Srivari Honda showroom Alathur Road Pazhayannur Pin-680587 Ph- 9645261763', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a2c4efba7c1c20c6'),
('IN236', 'kunju_vandi', NULL, 'https://www.instagram.com/kunju_vandi/', 'instagram', 'nano', ARRAY['diecast']::text[], 20000, 'Enthusiasts', NULL, '+919497009568', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-20efa987cd483aaa'),
('IN237', 'nerdarenaofficial', NULL, 'https://www.instagram.com/nerdarenaofficial/', 'instagram', 'nano', ARRAY['toys', 'diecast']::text[], 5000, 'Enthusiasts/kids', 'Bandra', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0c313168969bea0f'),
('IN238', 'toyloft.in', NULL, 'https://www.instagram.com/toyloft.in/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], 1500, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-67ce3e2c37ec0b48'),
('IN239', 'boythatcreates', 'Aryan Kotadia', 'https://www.instagram.com/boythatcreates/', 'instagram', 'nano', ARRAY['vlogs', 'diecast', 'rc']::text[], 15000, 'Enthusiasts', 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1c81adc78919ef73'),
('IN240', 'streetcandyminiature', NULL, 'https://www.instagram.com/streetcandyminiature/', 'instagram', 'nano', ARRAY['diecast', 'tech']::text[], 6000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-338234812edba353')
ON CONFLICT (influencer_code) DO NOTHING;
