-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN401', 'Mrsneakofficial', NULL, 'https://www.youtube.com/@Mrsneakofficial/shorts', 'youtube', 'micro', ARRAY['unboxing', 'review', 'tech', 'rc']::text[], 30000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3e83b0f6f00a8244'),
('IN402', 'chatpattoytv', 'Rayan', 'https://www.youtube.com/@chatpattoytv', 'youtube', 'brand', ARRAY['rc', 'review', 'cinematic', 'tech']::text[], 300000, 'enthusiasts', NULL, NULL, NULL, 'chatpattoytv@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-2964705ca56f9a54'),
('IN403', 'kochi_vlogger', NULL, 'https://www.instagram.com/kochi_vlogger/reels/', 'instagram', 'macro', ARRAY['vlogs', 'review']::text[], 25000, 'general', 'Kochi', '+918590891499', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-310429c8225b786d'),
('IN404', 'nagercoil_trueliving', 'Aravinth Nagercoil', 'https://www.instagram.com/nagercoil_trueliving/reels/', 'instagram', 'nano', ARRAY['vlogs', 'review']::text[], 15000, 'general', 'Nagercoil', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-00b73bef5b7a4797'),
('IN405', 'rachna_gangatkar', 'Rachna Gangatkar', 'https://www.instagram.com/rachna_gangatkar/reels/', 'instagram', 'micro', ARRAY['auto', 'vlogs']::text[], 40000, 'general/enthusiasts', 'Bangalore', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d79ebc3d41e38e7a'),
('IN406', 'that__smokin__thing', 'Barath Sudhan K', 'https://www.instagram.com/that__smokin__thing/reels/', 'instagram', 'macro', ARRAY['vlogs', 'unboxing', 'review', 'diecast']::text[], 60000, 'general/enthusiasts', NULL, '+916379658885', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-036c266627c40780'),
('IN407', 'adiljal', 'ADIL JAL DARUKHANAWALA', 'https://www.instagram.com/adiljal/reels/', 'instagram', 'micro', ARRAY['review', 'unboxing', 'auto', 'diecast', 'rc']::text[], 25000, 'enthusiasts', NULL, '+919823534638', NULL, 'adiljal@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-5ec970bcb89da897'),
('IN408', 'khrishaadeals', NULL, 'https://www.instagram.com/khrishaadeals/reels/', 'instagram', 'macro', ARRAY['diecast', 'rc', 'review', 'unboxing', 'toys']::text[], 80000, 'enthusiasts', 'Noida', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b5b1f8e9380f4dba'),
('IN409', 'urvishkaushik_', 'Urvish Kaushik', 'https://www.instagram.com/urvishkaushik_/', 'instagram', 'micro', ARRAY['auto', 'cinematic', 'vlogs']::text[], 1000000, 'enthusiasts', NULL, NULL, NULL, 'urvishkaushik6@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-de62e4ddf29e24f3'),
('IN410', 'customclans', NULL, 'https://www.instagram.com/customclans/reels/', 'instagram', 'macro', ARRAY['rc', 'tech', 'diecast', 'toys', 'unboxing', 'review']::text[], 20000, 'enthusiasts', 'nagpur', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ad69cad78cbcc1bc'),
('IN411', 'ogmini_official', NULL, 'https://www.instagram.com/ogmini_official/reels/', 'instagram', 'nano', ARRAY['diecast', 'review', 'unboxing']::text[], 40000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e9b459516e18e6b6'),
('IN412', '_rachnax0', 'Rachna Gowda', 'https://www.instagram.com/_rachnax0/', 'instagram', 'micro', ARRAY['vlogs', 'auto']::text[], 200000, 'general/enthusiasts', 'bangalore', NULL, NULL, 'rachnaa087@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-e6dc9b1a83869373'),
('IN413', 'aryan.dhandhania', 'Aryan', 'https://www.instagram.com/aryan.dhandhania/reels/', 'instagram', 'nano', ARRAY['auto', 'vlogs']::text[], 35000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-afee83a0c65febc3'),
('IN414', 'anunaysood', 'Anunay Sood', 'https://www.instagram.com/anunaysood/reels/', 'instagram', 'brand', ARRAY['vlogs', 'tech', 'auto']::text[], 1000000, 'travel/enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2e227d0c9971e53f'),
('IN415', 'techburner', NULL, 'https://www.instagram.com/techburner/', 'instagram', 'brand', ARRAY['unboxing', 'review', 'tech', 'auto']::text[], 1000000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-73c84c9e0cb065f5'),
('IN416', 'bike.pagglait', 'Rutuja', 'https://www.instagram.com/bike.pagglait/', 'instagram', 'nano', ARRAY['vlogs', 'auto']::text[], 250000, 'enthusiasts', NULL, '+917741945444', 'Blueridge, B4 1302, Hinjewadi, Pune Pin- 411057', 'bike.pagglait8000@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b307c35e1f0dc027'),
('IN417', 'puneet_khaneja', 'Puneet Khaneja', 'https://www.instagram.com/puneet_khaneja/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 50000, 'general', 'Gurgaon', '+917015521347', NULL, 'puneetkhaneja20@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-8fb184de4b1a619d'),
('IN418', 'leki_goswami01', 'LAKSHMAN GOSWAMI', 'https://www.instagram.com/leki_goswami01/', 'instagram', 'brand', ARRAY['auto', 'vlogs', 'review', 'ugc']::text[], 1000000, 'enthusiasts/general', 'Karnataka, Rajasthan, Tamil Nadu', '+916363927490', NULL, 'laxmanbharti41@gmail.com', NULL, 'Manager', NULL, 'master', 'omnipres-inf-76b5e70e5a3ec133'),
('IN419', 'piston_bells_', 'Akhil Vijayan', 'https://www.instagram.com/piston_bells_/reels/', 'instagram', 'nano', ARRAY['review', 'tech', 'vlogs']::text[], 15000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-087ab85a10ad945f'),
('IN420', 'nirmalkrishnan', 'Nirmal Krishnan', 'https://www.instagram.com/nirmalkrishnan/reels/', 'instagram', 'macro', ARRAY['auto', 'vlogs', 'review']::text[], 200000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c09ced83ff6be4e9'),
('IN421', 'shwetachithrode', 'Shweta Chithrode', 'https://www.instagram.com/shwetachithrode/reels/', 'instagram', 'nano', ARRAY['auto', 'vlogs']::text[], 15000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-bd65fed7b755f511'),
('IN422', 'kiddies_scoop', 'Ishan, Orhan', 'https://www.instagram.com/kiddies_scoop/reels/', 'instagram', 'macro', ARRAY['unboxing', 'vlogs', 'auto', 'rc']::text[], 100000, 'kids/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b531f7257cd3437c'),
('IN423', 'abinbabsabraham', NULL, 'https://www.instagram.com/abinbabsabraham/reels/', 'instagram', 'brand', ARRAY['auto', 'toys']::text[], 300000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b94975e01ea41f2b'),
('IN424', '_l.i.v.e.w.i.l.d_', 'Yuva Sush', 'https://www.instagram.com/_l.i.v.e.w.i.l.d_/reels/', 'instagram', 'micro', ARRAY['auto', 'review', 'unboxing', 'vlogs']::text[], 25000, 'enthusiasts', 'Chennai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f330a34cc5b37d26'),
('IN425', 'tintin_vlogss', 'Nitin Rathore', 'https://www.instagram.com/tintin_vlogss/reels/', 'instagram', 'nano', ARRAY['diecast', 'unboxing', 'review']::text[], 13000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ae92e2ed5351a7bf'),
('IN426', 'thatpotatoface5', 'Sameeha Mariam', 'https://www.instagram.com/thatpotatoface5/reels/', 'instagram', 'macro', ARRAY['review', 'ugc', 'vlogs']::text[], 400000, 'general', NULL, NULL, NULL, 'thatpotatoface5@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-8361074eab032af7'),
('IN427', 'diecastduotales', NULL, 'https://www.instagram.com/diecastduotales/reels/', 'instagram', 'nano', ARRAY['diecast', 'unboxing', 'review']::text[], 5000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b02d927cce1b40a5'),
('IN428', 'kaustubh.purohit.33', 'Kaustubh Purohit', 'https://www.instagram.com/kaustubh.purohit.33/reels/', 'instagram', 'nano', ARRAY['diecast', 'vlogs']::text[], 5000, 'enthusiasts/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-88666b2bcc2fc086'),
('IN429', 'devipraseeda.vlogs', 'Devipraseeda', 'https://www.instagram.com/devipraseeda.vlogs/reels/', 'instagram', 'nano', ARRAY['vlogs', 'review', 'diecast']::text[], 20000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-20354fad1e286ca8'),
('IN430', 'foodie_.chef', NULL, 'https://www.instagram.com/foodie_.chef/reels/', 'instagram', 'macro', ARRAY['vlogs', 'rc', 'diecast']::text[], 45000, 'enthusiasts', 'kerala, goa', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a702c5d6ee261bc5'),
('IN431', 'alan_elz', NULL, 'https://www.instagram.com/alan_elz/reels/', 'instagram', 'macro', ARRAY['review', 'ugc', 'diecast']::text[], 45000, 'fashion enthusisast', NULL, NULL, NULL, '𝐜𝐨𝐥𝐥𝐚𝐛𝐬.𝐚𝐥𝐚𝐧𝐞𝐥𝐳@𝐠𝐦𝐚𝐢𝐥.𝐜𝐨𝐦', NULL, NULL, NULL, 'master', 'omnipres-inf-7866bfc1d906efca'),
('IN432', 'tronplayworld', NULL, 'https://www.instagram.com/tronplayworld/reels/', 'instagram', 'nano', ARRAY['diecast', 'rc', 'toys']::text[], 2000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-676fe4aac44c13ac'),
('IN433', 'ishpreetbalbir', 'Ishpreet Balbir', 'https://www.instagram.com/ishpreetbalbir/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 80000, 'general', 'mumbai', NULL, NULL, 'ishpreetbalbir@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-f11062ddc1e4407c'),
('IN434', 'cyrusdhabhar', 'Cyrus Dhabhar', 'https://www.instagram.com/cyrusdhabhar/reels/', 'instagram', 'micro', ARRAY['auto', 'review']::text[], 40000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e3cda1079187d96e'),
('IN435', 'ganikgagan', 'Gagan Choudhary', 'https://www.instagram.com/ganikgagan/reels/', 'instagram', 'macro', ARRAY['auto', 'review', 'tech']::text[], 400000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d7066058b63fd95d'),
('IN436', 'akhilhemadri', 'Akhil Yadav', 'https://www.instagram.com/akhilhemadri/reels/', 'instagram', 'nano', ARRAY['auto', 'vlogs']::text[], 100000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4db6de09ec4077f9'),
('IN437', 'trakintech', 'Arun Prabhudesai', 'https://www.instagram.com/trakintech/reels/', 'instagram', 'brand', ARRAY['review', 'unboxing', 'tech']::text[], 1000000, 'enthusiasts', NULL, NULL, NULL, 'business@trak.in', NULL, NULL, NULL, 'master', 'omnipres-inf-5b65918e8e72f31f'),
('IN438', 'sharmajitechnical', 'Praval Sharma', 'https://www.instagram.com/sharmajitechnical/reels/', 'instagram', 'micro', ARRAY['review', 'tech']::text[], 10000, 'enthusiasts', 'Rajasthan', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f8f2978936db8a3f'),
('IN439', 'tech_unboxing007', 'Abhijeet Desai', 'https://www.instagram.com/tech_unboxing007/reels/', 'instagram', 'macro', ARRAY['review', 'tech', 'unboxing']::text[], 12000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-954c796f3b3ce251'),
('IN440', 'techwith_surya', 'P Surya', 'https://www.instagram.com/techwith_surya/reels/', 'instagram', 'macro', ARRAY['unboxing', 'review', 'tech']::text[], 60000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6f4e890e5e7b0ecf')
ON CONFLICT (influencer_code) DO NOTHING;
