-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN521', 'Crazy Indian', NULL, 'https://www.youtube.com/@CrazyIndianshorts89/shorts', 'youtube', 'macro', ARRAY['rc', 'vlogs', 'review']::text[], 20000, 'rc reviews', NULL, NULL, NULL, 'Sahuvivek2560@Gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-90abfb81d19f3fde'),
('IN522', 'amsuv', 'Suvam Sahoo', 'https://www.instagram.com/amsuv/reels/', 'instagram', 'micro', ARRAY['review', 'finds', 'vlogs']::text[], 15000, 'General content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0313021ec235c458'),
('IN523', 'Gadget Zone', NULL, 'https://www.youtube.com/@TheRealGadgetZone', 'youtube', 'macro', ARRAY['review', 'finds', 'unboxing', 'tech']::text[], 10000, 'Tech reviews', NULL, NULL, NULL, 'hm97983@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-906242520c67724a'),
('IN524', 'Miniature Automobiles', 'Nishchay Sharma', 'https://www.youtube.com/@MiniatureAutomobiles/videos', 'youtube', 'macro', ARRAY['cinematic', 'toys']::text[], 150000, 'diecast reviews', NULL, NULL, NULL, 'Nisfbruno@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-24eb58465869f912'),
('IN525', 'Onespot Tech', NULL, 'https://www.youtube.com/@OnespotTech', 'youtube', 'macro', ARRAY['unboxing', 'review', 'finds', 'tech']::text[], 25000, 'general reviews', NULL, NULL, NULL, 'tech@onespotgaming.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d4f27c77d9ecfb1e'),
('IN526', 'Harish Shorts', 'Harish Choudhary', 'https://www.youtube.com/@HarishShorts/shorts', 'youtube', 'macro', ARRAY['toys', 'review', 'unboxing', 'finds']::text[], 400000, 'general reviews', 'Chhattisgarh', NULL, NULL, 'multipurposevid@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-303ffd024d61ac4e'),
('IN527', 'acha_sa_naam', 'Aayush Bisht', 'https://www.instagram.com/acha_sa_naam/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], 10000, 'trekking/vlogs', NULL, '+919518942996', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e59448ac562dd5f1'),
('IN528', 'decorstation_store', NULL, 'https://www.instagram.com/decorstation_store/reels/', 'instagram', 'nano', ARRAY['toys']::text[], 8000, 'toy reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c48cc13426fbbe23'),
('IN529', 'deskco.in', NULL, 'https://www.instagram.com/deskco.in/', 'instagram', 'nano', ARRAY['toys', 'unboxing']::text[], 25000, 'toy reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ad4bb6036d138782'),
('IN530', 'daddydronesmumbai', 'Ashraf Shaikh', 'https://www.instagram.com/daddydronesmumbai/', 'instagram', 'store', ARRAY['unboxing', 'review', 'toys', 'rc']::text[], 60000, 'rc/toys', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ca9b5c6802c30f1e'),
('IN531', 'singhsahabtoys', NULL, 'https://www.instagram.com/singhsahabtoys/', 'instagram', 'store', ARRAY['toys', 'rc', 'review', 'unboxing']::text[], 12000, 'general toy reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a97ff2d20dd57b2a'),
('IN532', 'ig_razzee', 'SHUBHAM SACHAN', 'https://www.instagram.com/ig_razzee/', 'instagram', 'micro', ARRAY['toys', 'rc', 'vlogs']::text[], 100000, 'rc car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9e1b9352999270b2'),
('IN533', 'robonist', NULL, 'https://www.instagram.com/robonist/', 'instagram', 'macro', ARRAY['rc', 'toys', 'tech']::text[], 15000, 'general tech reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ae9ac64519f4fd73'),
('IN534', 'shabeeb.yet', NULL, 'https://www.instagram.com/shabeeb.yet/', 'instagram', 'micro', ARRAY['rc', 'toys', 'vlogs']::text[], 200000, 'rc car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-552f12b731f08cbe'),
('IN535', 'be_kiddish', NULL, 'https://www.instagram.com/be_kiddish/reels/', 'instagram', 'micro', ARRAY['toys', 'rc', 'finds']::text[], 10000, 'toy store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-be37cc69da128bc6'),
('IN536', '___toinokiddo___', 'Toino', 'https://www.instagram.com/___toinokiddo___/', 'instagram', 'micro', NULL, 50000, 'car content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-23f9704b80bb6fcd'),
('IN537', 'AndreoBee', NULL, 'https://www.youtube.com/@AndreoBee/videos', 'youtube', 'macro', ARRAY['finds', 'vlogs']::text[], 800000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-97438ded100b495a'),
('IN538', 'SHEF', NULL, 'https://www.youtube.com/@SHEFALIRAWAT', 'youtube', 'macro', ARRAY['review', 'finds', 'ugc']::text[], 450000, 'amazon finds', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c53a5a20fe0f8f32'),
('IN539', 'Mr Local', NULL, 'https://www.youtube.com/@mrlocaltamil/shorts', 'youtube', 'macro', ARRAY['unboxing', 'review', 'finds', 'vlogs']::text[], 500000, 'general reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f61c1d72b548203f'),
('IN540', 'Mad Vise', NULL, 'https://www.youtube.com/@Madvise007/shorts', 'youtube', 'macro', ARRAY['finds', 'vlogs', 'tech']::text[], 600000, 'tech/general reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-4a1aaf805f9f1663'),
('IN541', 'Ayush Verma', NULL, 'https://www.youtube.com/@AyushVerma', 'youtube', 'macro', ARRAY['vlogs']::text[], 80000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-84902e3d76e415b9'),
('IN542', 'Mr Techpedia', NULL, 'https://www.youtube.com/@mrtechpedia/videos', 'youtube', 'macro', ARRAY['tech', 'review']::text[], 200000, 'Tech reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-aaa32c3bf6aa4ce6'),
('IN543', 'prime_fabby', NULL, 'https://www.instagram.com/prime_fabby/', 'instagram', 'micro', ARRAY['review', 'finds', 'tech']::text[], 80000, 'Tech reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c9f1d615932790ab'),
('IN544', 'vickyvlogs02', NULL, 'https://www.instagram.com/vickyvlogs02/', 'instagram', 'micro', NULL, 150000, 'bike content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9946ddbf9432ebf8'),
('IN545', 'adhisha_tiwari_official', NULL, 'https://www.instagram.com/adhisha_tiwari_official/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 20000, 'Kids content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-4793ae137c857f0b'),
('IN546', 'nizamphotographs', NULL, 'https://www.instagram.com/nizamphotographs/reels/', 'instagram', 'micro', ARRAY['cinematic', 'vlogs']::text[], 10000, 'photography', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c219f0897fc36ab4'),
('IN547', 'santhosh.superstores', NULL, 'https://www.instagram.com/santhosh.superstores/', 'instagram', 'nano', NULL, 6000, 'toy store', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-397325b71e4a1fba'),
('IN548', 'gaurav_upadhyay07', NULL, 'https://www.instagram.com/gaurav_upadhyay07/', 'instagram', 'micro', NULL, 400000, 'general reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1e78c697ba369e7e'),
('IN549', 'yuvas.journal', NULL, 'https://www.instagram.com/yuvas.journal/', 'instagram', 'micro', ARRAY['review', 'finds']::text[], 150000, 'general finds', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-71a0f08809d44b1d'),
('IN550', 'almost.engineered', NULL, 'https://www.instagram.com/almost.engineered/', 'instagram', 'micro', ARRAY['vlogs']::text[], 20000, '3D print content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-65889704680c4c9b'),
('IN551', '_human.diaries_', NULL, 'https://www.instagram.com/_human.diaries_/', 'instagram', 'nano', ARRAY['vlogs', 'finds']::text[], 15000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6959f65aeb08969c'),
('IN552', 'aaru_sann', NULL, 'https://www.instagram.com/aaru_sann/', 'instagram', 'macro', ARRAY['vlogs', 'cinematic']::text[], 100000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-92124f664323b57b'),
('IN553', 'content.avr', 'Aditya Vardhan Rajput', 'https://www.instagram.com/content.avr/reels/', 'instagram', 'micro', NULL, 25000, 'content creation', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-671a89c308da07db'),
('IN554', 'thatsoshani', 'Shani', 'https://www.instagram.com/thatsoshani/', 'instagram', 'micro', ARRAY['ugc', 'finds', 'review']::text[], 50000, 'UGC content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d38e908844677ba6'),
('IN555', 'vijay_vox.in', NULL, 'https://www.instagram.com/vijay_vox.in/', 'instagram', 'nano', ARRAY['toys', 'diecast']::text[], 15000, 'general toy content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1027d9c8cc80d633'),
('IN556', 'thevarunmayya', 'Varun Mayya', 'https://www.instagram.com/thevarunmayya/', 'instagram', 'macro', ARRAY['tech', 'finds']::text[], 250000, 'Tech reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5f809884d6e648cf'),
('IN557', 'ayushman.pandita', 'Ayushman Pandita', 'https://www.instagram.com/ayushman.pandita/', 'instagram', 'macro', ARRAY['vlogs', 'finds', 'ugc']::text[], 150000, 'general content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3c0a470efeca2d05'),
('IN558', 'billunboxed', 'Bilal Khan', 'https://www.instagram.com/billunboxed/reels/', 'instagram', 'micro', ARRAY['finds', 'review', 'vlogs']::text[], 25000, 'general finds', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-4bf95030a7f6d669'),
('IN559', 'techweu', NULL, 'https://www.instagram.com/techweu/reels/', 'instagram', 'micro', ARRAY['review', 'tech', 'vlogs']::text[], 5000, 'gaming content', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a456d5e0a465328f'),
('IN560', '_mr.swashbuckler_', NULL, 'https://www.instagram.com/_mr.swashbuckler_/reels/', 'instagram', 'macro', ARRAY['finds', 'vlogs']::text[], 250000, 'food and travel', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-7ae9571e17ed5bd9')
ON CONFLICT (influencer_code) DO NOTHING;
