-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN241', 'making__dude', NULL, 'https://www.instagram.com/making__dude/', 'instagram', 'nano', ARRAY['tech', 'toys']::text[], 20000, 'Enthusiasts', 'Kerala', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d9d2c82842de53db'),
('IN242', 'toycra', NULL, 'https://www.instagram.com/toycra/', 'instagram', 'macro', ARRAY['toys']::text[], 10000, 'Parents/ Kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7d5851ed9532bf5a'),
('IN243', 'minitorque_', NULL, 'https://www.instagram.com/minitorque_/', 'instagram', 'nano', ARRAY['unboxing', 'diecast']::text[], 25000, 'Enthusiasts', NULL, '+919544336522', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3a8b55f15d6c5e62'),
('IN244', '__jainsaloni__', 'Saloni Jain', 'https://www.instagram.com/__jainsaloni__/', 'instagram', 'nano', ARRAY['unboxing', 'review', 'diecast', 'rc']::text[], 100000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a34855fd97fc583e'),
('IN245', 'madam_collectibles', 'Neha', 'https://www.instagram.com/madam_collectibles/', 'instagram', 'nano', ARRAY['diecast']::text[], 2000, 'Enthusiasts', 'Delhi', '+919220738745', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c9041bdf9c6ec414'),
('IN246', 'toybuzz46', NULL, 'https://www.instagram.com/toybuzz46/', 'instagram', 'nano', ARRAY['toys', 'rc', 'unboxing', 'diecast']::text[], 15000, 'Enthusiasts', 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-5f95820983fe69a1'),
('IN247', 'sabin_madwheelz', NULL, 'https://www.instagram.com/sabin_madwheelz/', 'instagram', 'nano', ARRAY['diecast', 'vlogs', 'review']::text[], 15000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b5ba930112f55656'),
('IN248', 'etrendingtoys', NULL, 'https://www.instagram.com/etrendingtoys/', 'instagram', 'micro', ARRAY['toys', 'rc', 'diecast']::text[], 12000, 'Enthusiasts/kids', 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4f14a06c41fbe997'),
('IN249', 'mimiko_toy_store', NULL, 'https://www.instagram.com/mimiko_toy_store/', 'instagram', 'nano', ARRAY['diecast', 'toys', 'rc']::text[], 15000, 'general/enthusiasts/kids', 'Pimpri, Pune', '+918087558028', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-564bbf23ac164d7e'),
('IN250', 'collectict', NULL, 'https://www.instagram.com/collectict/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], 5000, 'Enthusiasts/kids', 'Calicut', '+916282000727', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c8f6d9a63a3440ba'),
('IN251', 'frizbeekochi', NULL, 'https://www.instagram.com/frizbeekochi/', 'instagram', 'micro', ARRAY['rc', 'diecast', 'review', 'toys']::text[], 25000, 'Enthusiasts', NULL, '+9847868999934948302085929986009388998300', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-45c1cbb759fbd14f'),
('IN252', 'superherotoystore', NULL, 'https://www.instagram.com/superherotoystore/', 'instagram', 'nano', ARRAY['toys']::text[], 2000, 'Collectible Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cafd88b96ea240b8'),
('IN253', 'anime_toys_and_wheels', NULL, 'https://www.instagram.com/anime_toys_and_wheels/', 'instagram', 'nano', ARRAY['unboxing', 'rc', 'diecast', 'toys']::text[], 15000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b31c81624d9625cd'),
('IN254', 'diecast_hub_757', 'Anuj Patil', 'https://www.instagram.com/diecast_hub_757/', 'instagram', 'nano', ARRAY['cinematic', 'diecast']::text[], 50000, 'Enthusiasts', 'Maharashtra', '+918999342288', 'DISHA SILVER WOODS. HARSUL T POINT FLAT NO 104 BUILDING NO-B3. AURANGABAD MAHARASHTRA. PINCODE-431002', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-08b614b1b30621c7'),
('IN255', 'diecast_customs_goa', 'Bibiano Alex Dcosta', 'https://www.instagram.com/diecast_customs_goa/', 'instagram', 'nano', ARRAY['unboxing', 'diecast']::text[], 4000, 'Enthusiasts', NULL, '+919158094672', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b6438efaa7ad51e2'),
('IN256', 'pickbesttoys', NULL, 'https://www.instagram.com/pickbesttoys/', 'instagram', 'nano', ARRAY['toys', 'diecast']::text[], 2000, 'Kids/Adults/Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e4c97af7ea6bf847'),
('IN257', 'hellokidology', NULL, 'https://www.instagram.com/hellokidology/', 'instagram', 'nano', ARRAY['toys', 'rc']::text[], 2500, 'kids/Parents', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-207aa7bcff1a7594'),
('IN258', 'cloudtech_10', 'Sagar', 'https://www.instagram.com/cloudtech_10/', 'instagram', 'macro', ARRAY['rc', 'review', 'unboxing', 'diecast', 'toys']::text[], 40000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-36666542748702ec'),
('IN259', 'katta_kompany', NULL, 'https://www.instagram.com/katta_kompany/', 'instagram', 'nano', ARRAY['unboxing', 'review', 'diecast', 'cinematic', 'rc']::text[], 25000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4e2abc70b4506224'),
('IN260', 'jinocyriac', 'Jino Cyriac', 'https://www.instagram.com/jinocyriac', 'instagram', 'macro', ARRAY['rc', 'cinematic', 'tech', 'review']::text[], 200000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2abd43d64ae35cb3'),
('IN261', 'najeebrkp', 'Najeeb Rehman KP', 'https://www.instagram.com/p/DFklnQnSjw7/', 'instagram', 'macro', ARRAY['review', 'unboxing', 'diecast', 'rc', 'auto']::text[], 150000, 'Enthusiasts', NULL, '+917736803803', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c525f1c650147fdf'),
('IN262', '_human.diaries_', 'AKSHAY SREEDHAR', 'https://www.instagram.com/_human.diaries_/', 'instagram', 'nano', ARRAY['diecast', 'ugc']::text[], 20000, 'Enthusiasts/adult', 'Trivandrum', '+916282150282', 'THENPARAYIL, MPANRA-61, LANE 7, M.P APPAN ROAD, NEAR TO KS HOME AQUARIUM, VAZHUTHACAUD, TRIVANDRUM, 695014', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3f977cd897a394f1'),
('IN263', 'nithinnoble', 'Nithin Noble', 'https://www.instagram.com/nithinnoble/', 'instagram', 'nano', ARRAY['review', 'rc', 'diecast', 'cinematic']::text[], 20000, 'Enthusiasts/adult', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b20697cdeb177a4f'),
('IN264', 'ig.wizardsir_', 'Abhiraj', 'https://www.instagram.com/ig.wizardsir_/', 'instagram', 'nano', ARRAY['diecast']::text[], 20000, 'Enthusiasts/gamer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4dee23ec2ae0b929'),
('IN265', 'cinemayumsarkeettum', 'Cinemayum Sarkeettum', 'https://www.instagram.com/cinemayumsarkeettum/', 'instagram', 'nano', ARRAY['diecast', 'cinematic', 'rc']::text[], 2500, 'general/enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4fe023a179d9e38a'),
('IN266', 'hiiqify', NULL, 'https://www.instagram.com/hiiqify/', 'instagram', 'nano', ARRAY['tech']::text[], 15000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f51b1bb5edad1716'),
('IN267', 'ubayyibnuummar', 'Ubayy ibnu ummar K', 'https://www.instagram.com/ubayyibnuummar/', 'instagram', 'nano', ARRAY['tech', 'auto', 'diecast']::text[], 15000, 'Enthusiasts', 'Kerala', '+919061556004', 'Khanirayi house, vellayur po aakkumparil 679327. Land mark : near akkumpar bridge', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a5d6a0378d1341c1'),
('IN268', 'its_bharathhhh', 'Bharath', 'https://www.instagram.com/its_bharathhhh/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'review']::text[], 20000, 'general/enthusiasts', 'Madras', '+916374162066', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-88f42d220087ec96'),
('IN269', 'rasimomandbaby', NULL, 'https://www.instagram.com/rasimomandbaby/', 'instagram', 'nano', ARRAY['toys', 'rc']::text[], 5000, 'Parents/ Kids', 'Thoothukudi', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2dbf01c08d226d57'),
('IN270', 'riyansh_toys', NULL, 'https://www.instagram.com/riyansh_toys', 'instagram', 'nano', ARRAY['rc', 'toys', 'diecast']::text[], 1500, 'kids', 'Pondicherry', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c0e8e7b1e1f4e733'),
('IN271', 'kalapistores', NULL, 'https://www.instagram.com/kalapistores/', 'instagram', 'nano', ARRAY['unboxing', 'rc', 'diecast']::text[], 3000, 'Enthusiasts/kids', 'Mumbai', '+919820107345', 'Kalapi Stores Metro House,Opp titan world ,Near Regal Bust stop, Colaba causway, Mumbai 400001, Maharashtra State, India.', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-831ddc1107c0b51b'),
('IN272', 'mini.garage164', NULL, 'https://www.instagram.com/mini.garage164/', 'instagram', 'micro', ARRAY['diecast', 'unboxing', 'cinematic', 'rc']::text[], 10000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9cdacf5b2335b154'),
('IN273', 'one_life_live__it', 'Shifu Rojan Roy D''cruz', 'https://www.instagram.com/one_life_live__it/', 'instagram', 'micro', ARRAY['rc', 'review', 'diecast', 'auto']::text[], 75000, 'Enthusiasts', NULL, '+919567094919', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-140f6fc70f80f261'),
('IN274', 'youcliq', NULL, 'https://www.instagram.com/youcliq/', 'instagram', 'micro', ARRAY['cinematic', 'unboxing', 'rc', 'diecast']::text[], 15000, 'Enthusiasts', NULL, '+919658916916', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1b4474c25a5aa738'),
('IN275', 'artist_machan_', NULL, 'https://www.instagram.com/artist_machan_/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'cinematic', 'tech']::text[], 50000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-afdc50382372d1af'),
('IN276', 'artistmachan_official', 'Jomon Jo', 'https://www.instagram.com/artistmachan_official/', 'instagram', 'nano', ARRAY['cinematic', 'rc', 'diecast']::text[], 25000, 'Enthusiasts/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-837d0e5afe14cae9'),
('IN277', 'cherry_chaser__', NULL, 'https://www.instagram.com/cherry_chaser__/', 'instagram', 'nano', ARRAY['auto']::text[], 50000, 'Enthusiasts', 'Kerala', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-5f2015c9abf7c999'),
('IN278', 'harshitchajjed', 'Harshit Chajjed', 'https://www.instagram.com/harshitchajjed/', 'instagram', 'macro', ARRAY['vlogs']::text[], 200000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-77ad1752d06ff397'),
('IN279', 'artofgauri', 'Gauri Rajput', 'https://www.instagram.com/artofgauri/', 'instagram', 'macro', ARRAY['vlogs', 'diecast']::text[], 7000, 'gifting/general', NULL, '+918860405415', NULL, 'rajputgauri13@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-db785742d3167ab5'),
('IN280', 'typicalmalayali', NULL, 'https://www.instagram.com/typicalmalayali/', 'instagram', 'nano', ARRAY['unboxing', 'review', 'rc', 'diecast', 'auto']::text[], 60000, 'Enthusiasts/general', NULL, NULL, NULL, 'typicalgau@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-d9ca1e2c0e943339')
ON CONFLICT (influencer_code) DO NOTHING;
