-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN681', 'abidaranaaa', NULL, 'https://www.instagram.com/abidaranaaa/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f50fa6f6b64bb632'),
('IN682', 'frames_of_ram_', NULL, 'https://www.instagram.com/frames_of_ram_/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-be43c152c02ecc3e'),
('IN683', 'aditya.thakare21', NULL, 'https://www.instagram.com/aditya.thakare21/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7781cb9b693a8acc'),
('IN684', 'vigneshkae', NULL, 'https://www.instagram.com/vigneshkae/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f14819c74b64ab30'),
('IN685', 'spiktec_', NULL, 'https://www.instagram.com/spiktec_/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-df03534f818170dd'),
('IN686', 'random_baniya', NULL, 'https://www.instagram.com/random_baniya/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f9ed5386101d18eb'),
('IN687', 'bmbyte', NULL, 'https://www.instagram.com/bmbyte/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c9dc7439856501c2'),
('IN688', 'vignesh_mindset', NULL, 'https://www.instagram.com/vignesh_mindset/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-fc507c9005fa0fc2'),
('IN689', 'vmdaftab', NULL, 'https://www.instagram.com/vmdaftab/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-26e3319612030e46'),
('IN690', 'sehajcantsehanymoree', NULL, 'https://www.instagram.com/sehajcantsehanymoree/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-df1d26ff367bbd0f'),
('IN691', 'waitwhatwithkishan', NULL, 'https://www.instagram.com/waitwhatwithkishan/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7b22f4b67702f42b'),
('IN692', 'creagenixkannada', NULL, 'https://www.instagram.com/creagenixkannada/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f4e3a029ebce0d9b'),
('IN693', 'sparknherd', NULL, 'https://www.instagram.com/sparknherd/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9d70c939c338a4f7'),
('IN694', 'bizdecoded.in', NULL, 'https://www.instagram.com/bizdecoded.in/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d6add1e5df4ccaa4'),
('IN695', 'bvrbreezy', NULL, 'https://www.instagram.com/bvrbreezy/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-dff8b928af156689'),
('IN696', 'samadhkhatri', NULL, 'https://www.instagram.com/samadhkhatri/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ab5ae81cd7c274b9'),
('IN697', 'myselfrachit', NULL, 'https://www.instagram.com/myselfrachit/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a4c1715bbcee9a19'),
('IN698', 'kydyuzhini', NULL, 'https://www.instagram.com/kydyuzhini/reels/', 'instagram', 'macro', ARRAY['finds', 'review', 'unboxing', 'tech']::text[], 10000000, 'finds/reviews', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3ba9b3a36f142be1'),
('IN699', 'lifestyle_with_drisha', NULL, 'https://www.instagram.com/lifestyle_with_drisha/', 'instagram', 'micro', NULL, 150000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-299ff70cee43cfde'),
('IN700', 'vnmomjourney', NULL, 'https://www.instagram.com/vnmomjourney/', 'instagram', NULL, NULL, 100000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ed44b04c502fec40'),
('IN701', 'theanurags', NULL, 'https://www.instagram.com/theanurags/', 'instagram', NULL, NULL, 200000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7ef19a156b2293ef'),
('IN702', 'technicalguruji', NULL, 'https://www.instagram.com/technicalguruji/', 'instagram', NULL, NULL, 600000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d22ac989c4488077'),
('IN703', 'themermaidscales', NULL, 'https://www.instagram.com/themermaidscales/', 'instagram', NULL, NULL, 600000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-65310115109d758a'),
('IN704', 'shreyanka_patil31', NULL, 'https://www.instagram.com/shreyanka_patil31/', 'instagram', NULL, NULL, 2000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-48364906fb68d660'),
('IN705', 'Geekyranjit', NULL, 'https://www.youtube.com/geekyranjit', 'youtube', NULL, NULL, 75000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-73c7f2437871829a'),
('IN706', 'trakintech', NULL, 'https://www.instagram.com/trakintech/', 'instagram', NULL, NULL, 1000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-60279f5a4e0d8e89'),
('IN707', 'technoruhez', NULL, 'https://www.instagram.com/technoruhez/', 'instagram', NULL, NULL, 200000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4b415cdb1f1f01b8'),
('IN708', 'Sharmaji Technical', NULL, 'https://www.instagram.com/sharmajitechnical/', 'instagram', NULL, NULL, 15000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7bd57023578cd13b'),
('IN709', 'theabhisheksagar', NULL, 'https://www.instagram.com/theabhisheksagar/', 'instagram', NULL, NULL, 50000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-101d6ef2d8e902df'),
('IN710', 'Techno Vedant', NULL, 'https://www.youtube.com/channel/UC2ZMiuXsWi9xrm66WEBPuZQ', 'youtube', NULL, NULL, 10000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-7d3b0911b32387a9'),
('IN711', 'mrwhosetheboss', NULL, 'https://www.instagram.com/mrwhosetheboss/', 'instagram', NULL, NULL, 1000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-97c2cb5e7e4eb238'),
('IN712', '__prachibhandari__', 'Prachi Bhandari', 'https://www.instagram.com/__prachibhandari__/reels/', 'instagram', 'macro', NULL, 100000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e9122f030e0b4730'),
('IN713', 'sazzybaer', NULL, 'https://www.instagram.com/sazzybaer/reels/', 'instagram', 'micro', NULL, 300000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-81fb6a934881a381'),
('IN714', 'therajivmakhni', 'Rajiv Makhni', 'https://www.instagram.com/therajivmakhni/reels/', 'instagram', 'macro', NULL, 700000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-69efb7639362777f'),
('IN715', 'divyarajputofficial', 'Divya Singh', 'https://www.instagram.com/divyarajputofficial/reels/', 'instagram', 'micro', NULL, 100000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-fe1cf54370e81f2e'),
('IN716', 'bikewithgirl', 'Priyanka', 'https://www.instagram.com/bikewithgirl/reels/', 'instagram', 'macro', NULL, 3000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cca248edab1208ff'),
('IN717', 'budgetvlogger', 'NIHAL DANISH PH', 'https://www.instagram.com/budgetvlogger/reels/', 'instagram', 'micro', NULL, 1000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-58223eada5e59624'),
('IN718', 'foodie_doodless', 'PRACHI | DIKSHA', 'https://www.instagram.com/foodie_doodless/reels/', 'instagram', 'micro', NULL, 50000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-44409368e69a815e'),
('IN719', 'mishti.mehtaa', 'Mishti Mehta', 'https://www.instagram.com/mishti.mehtaa/reels/', 'instagram', 'macro', NULL, 300000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f2cdfddcb948eaca'),
('IN720', 'vishesh_satija', 'Vishesh Satija', 'https://www.instagram.com/vishesh_satija/reels/', 'instagram', NULL, NULL, 50000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2bc7ccccc70481b2')
ON CONFLICT (influencer_code) DO NOTHING;
