-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN1124', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-27a4fa3150965420'),
('IN1125', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-89717ad7d5997cec'),
('IN1126', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ca5253e5cd4055dd'),
('IN1127', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6884c2546ee4053a'),
('IN1128', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9864c4159109defe'),
('IN1129', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f62c59be5054af17'),
('IN1130', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d63b350f7a315a15'),
('IN1131', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-91a743a549e4f2e4'),
('IN1132', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-df044ee53c4d85ad'),
('IN1133', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6ad6e117eb6d1b28'),
('IN1134', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-edd16e277075d423'),
('IN1135', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-750aef135d5be61d'),
('IN1136', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-09939cbb682c867b'),
('IN1137', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-907ff666d29edac7'),
('IN1138', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d48a6e1c424f151b'),
('IN1139', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ab40327388d288ab'),
('IN1140', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6bdc63ce68314470'),
('IN1141', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-810b05326365ba5a'),
('IN1142', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-34132a591e0252d6'),
('IN1143', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4d6f747b2b803f7e'),
('IN1144', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-acaefe111826dc39'),
('IN1145', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-99bb1a3f0bcce912'),
('IN1146', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6d4ea55f1acc0a94'),
('IN1147', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b2c27464ee4ec5d8'),
('IN1148', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a1deffd052e0e4da'),
('IN1149', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d1c948617bfb2a54'),
('IN1150', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-90b99a2c656d7e5a'),
('IN1151', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-25eb132e762e01e4'),
('IN1152', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a7589732e8c8e020'),
('IN1153', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b485abaf6aa48bca'),
('IN1154', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-172d432e80dc6cc5'),
('IN1155', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d53d7b53e4fd2eb8'),
('IN1156', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-71ba20a6cd27302f'),
('IN1157', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-526971aa39159775'),
('IN1158', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-96dca69e03103734'),
('IN1159', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-29cd96f772cce646'),
('IN1160', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-24ac1bccdd2747df'),
('IN1161', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3308e95a691968f9'),
('IN1162', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2656e6a70b794494'),
('IN1163', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4b35eee59c0cc6f7')
ON CONFLICT (influencer_code) DO NOTHING;
