-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN281', 'reen4z', 'Reenaz Abdul', 'https://www.instagram.com/reen4z/', 'instagram', 'nano', ARRAY['unboxing', 'diecast', 'auto']::text[], 60000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2d7b58f5d8534ac9'),
('IN282', 'i.am.nafiz', 'Nafiz', 'https://www.instagram.com/p/DKEq2IhxFDk/', 'instagram', 'nano', ARRAY['tech', 'auto', 'diecast']::text[], 40000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-db51e7d0f48affb3'),
('IN283', '_the_red_raptor_', 'Bibin Chacko', 'https://www.instagram.com/_the_red_raptor_/', 'instagram', 'nano', ARRAY['rc', 'tech', 'cinematic', 'auto']::text[], 50000, 'Enthusiasts', 'Kerala', '+919074418583', 'Thanikuzhiyil house. Thiruvaniyoor (PO). Ernakulam. Kerala. Pin:682308', 'Engage after 15th Nov', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c930c13c769e0980'),
('IN284', 'thelittlebox_toys', NULL, 'https://www.instagram.com/thelittlebox_toys/', 'instagram', 'nano', ARRAY['toys', 'rc']::text[], 1000, 'kids/Parents', 'Kottayam', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-444c2b44ce768073'),
('IN285', 'diecast.kerala', 'Pranav G Nair', 'https://www.instagram.com/diecast.kerala/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'cinematic']::text[], 20000, 'Enthusiasts', 'Kerala', '+90487004989778134136', 'Theroppilly house. Annanad p.o. Chalakudy, Thrissur, Kerala - 680309', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f16fd4711f86beb2'),
('IN286', 'diecast._.cbe', NULL, 'https://www.instagram.com/diecast._.cbe/', 'instagram', 'nano', ARRAY['diecast']::text[], 10000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3493e543b1095391'),
('IN287', 'heart_racer_rc', 'Sathishkumar S', 'https://www.instagram.com/heart_racer_rc/', 'instagram', 'macro', ARRAY['unboxing', 'review', 'diecast']::text[], 200000, 'Enthusiasts', 'TamilNadu', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-58d5d71ef1f4a2bb'),
('IN288', 'views_of_balaji', 'Balaji C', 'https://www.instagram.com/views_of_balaji/', 'instagram', 'nano', ARRAY['diecast']::text[], 50000, 'Enthusiasts/general', 'TamilNadu', '+918056429831', '1/73  Lakshmi nagar , TVS nagar. Coimbatore , TAMIL NADU 641025', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-dc8a0c88d3be3072'),
('IN289', 'cargirlsindia', NULL, '(5) Instagram', 'instagram', 'brand', ARRAY['review', 'finds', 'cinematic', 'auto']::text[], 300000, 'Enthusiasts/general', 'Bangalore', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-162db544ad90f29a'),
('IN290', '8BitToast', NULL, 'https://www.youtube.com/@its8bittoast/shorts', 'youtube', 'nano', ARRAY['review', 'rc', 'tech']::text[], 3000, 'Enthusiasts/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ebe44c2e561f7e3f'),
('IN291', 'ShamshadMaker', NULL, 'https://www.youtube.com/@ShamshadMaker/shorts', 'youtube', 'brand', ARRAY['unboxing', 'rc']::text[], 800000, 'Enthusiasts', NULL, NULL, NULL, 'shamshadvideo@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-525097fe3a4f00ab'),
('IN292', 'desircgarage', NULL, 'https://www.youtube.com/@desircgarage/shorts', 'youtube', 'nano', ARRAY['rc', 'vlogs']::text[], 10000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8a77be5a1890eab6'),
('IN293', 'JMVTOYS', NULL, 'https://www.youtube.com/@JMVTOYS/shorts', 'youtube', 'macro', ARRAY['toys', 'rc', 'unboxing']::text[], 25000, 'Kids/Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-409f6a32671e362f'),
('IN294', 'Ruhulshorts', NULL, 'https://www.youtube.com/@Ruhulshorts1/shorts', 'youtube', 'brand', ARRAY['unboxing', 'rc', 'toys']::text[], 1000000, 'Kids/Enthusiasts', 'Assam', '+918822103156', 'Assam, Silchar, sonabarighat part:1 788013', 'abjollaskar118@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-2c06a6d5fe21be0e'),
('IN295', 'BigBuddyToys', NULL, 'https://www.youtube.com/@BigBuddyToys/shorts', 'youtube', 'nano', ARRAY['rc', 'unboxing', 'review', 'vlogs']::text[], 20000, 'Enthusiasts', NULL, NULL, NULL, 'bigbuddytoys@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-f2e4f7436acaffe6'),
('IN296', 'HackerJP', NULL, 'https://www.youtube.com/@HackerJP/shorts', 'youtube', 'brand', ARRAY['rc', 'tech', 'review', 'unboxing']::text[], 800000, 'Enthusiasts', NULL, NULL, NULL, 'hackerjpofficial@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-df35358947d73966'),
('IN297', 'techmastershort', 'Arvind Kharra', 'https://www.youtube.com/@techmastershort/shorts', 'youtube', 'brand', ARRAY['tech', 'review', 'vlogs', 'rc']::text[], 2000000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b274fb9ed22bd886'),
('IN298', 'manishkingdomshorts', NULL, 'https://www.youtube.com/@manishkingdomshorts/shorts', 'youtube', 'macro', ARRAY['rc']::text[], 35000, 'Enthusiasts', NULL, NULL, NULL, 'manishkingdom12@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-5338843c4de7ea41'),
('IN299', 'ARUV_ARMY', NULL, 'https://www.youtube.com/@ARUV_ARMY/shorts', 'youtube', 'macro', ARRAY['rc', 'tech', 'toys', 'review']::text[], 50000, 'Enthusiasts', NULL, NULL, NULL, 'rahul13apna@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-bc30ed28123a4bf4'),
('IN300', 'Afuniquetoyz12', NULL, 'https://www.youtube.com/@Afuniquetoyz12/shorts', 'youtube', 'macro', ARRAY['rc', 'toys']::text[], 80000, 'kids', NULL, NULL, NULL, 'abjalhussain9986@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-2dacb51541a24424'),
('IN301', 'ToyChitransh', NULL, 'https://www.youtube.com/@ToyChitransh/shorts', 'youtube', 'macro', ARRAY['rc', 'cinematic']::text[], 50000, 'Enthusiasts/kids', NULL, NULL, NULL, 'aarushsaini300@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-0298e4d8331b372d'),
('IN302', 'Samir96', 'Samir', 'https://youtube.com/@samir96?si=G7YJdQztzjnMBvu0', 'youtube', 'nano', ARRAY['rc', 'toys']::text[], 15000, 'kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-44c3406e98ece05c'),
('IN303', 'Rccarslover24', NULL, 'https://youtube.com/@rccarslover24?si=cSdyHevrdJHzRL7C', 'youtube', 'nano', ARRAY['rc']::text[], 15000, 'kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-872ee77b8a9a7401'),
('IN304', 'EazytronicShorts', 'Abdul Rahman', 'https://youtube.com/@eazytronicshorts?si=R8yx2q7xRxGOZJCr', 'youtube', 'micro', ARRAY['tech', 'unboxing']::text[], 30000, 'tech enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c8943aff17151c7b'),
('IN305', 'DeepToys78812', NULL, 'https://www.youtube.com/@DeepToys78812/shorts', 'youtube', 'nano', ARRAY['rc', 'toys']::text[], 20000, 'kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2b4870cf8fae7d2c'),
('IN306', 'SmartToysCapture', NULL, 'https://www.youtube.com/@SmartToysCapture/shorts', 'youtube', 'brand', ARRAY['rc', 'toys']::text[], 600000, 'kids', NULL, NULL, NULL, 'danishlaskar801145@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-198fde775307af43'),
('IN307', 'ApnaCreativeIdea', NULL, 'https://www.youtube.com/@ApnaCreativeIdea/shorts', 'youtube', 'brand', ARRAY['rc', 'tech']::text[], 30000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-011bb3fe1f7976b8'),
('IN308', 'Saidulketoys', NULL, 'https://www.youtube.com/@Saidulketoys/shorts', 'youtube', 'nano', ARRAY['rc', 'toys']::text[], 50000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-33c2894ba5139523'),
('IN309', 'ElectronicTricks786', 'Shahil', 'https://www.youtube.com/@ElectronicTricks786/shorts', 'youtube', 'macro', ARRAY['rc', 'review', 'unboxing', 'tech']::text[], 30000, 'Kids/Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-da06d7a8921f1799'),
('IN310', 'TanikSainVlogs', 'Tanik Sain', 'https://www.youtube.com/@TanikSainVlogs/shorts', 'youtube', 'nano', ARRAY['rc']::text[], 1000, 'Kids/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d288d8546135cf04'),
('IN311', 'RajibToy', 'Rajib', 'https://www.youtube.com/@RajibToy/shorts', 'youtube', 'micro', ARRAY['rc', 'toys', 'unboxing', 'review']::text[], 50000, 'Kids/Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0f61aff23d40cf1c'),
('IN312', 'muhd_thwalhath_', 'Beeraan', 'https://www.instagram.com/muhd_thwalhath_/reels/', 'instagram', 'nano', ARRAY['vlogs', 'rc', 'auto', 'review']::text[], 10000, 'Enthusiasts/general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-300ad1567c461bcd'),
('IN313', 'sekharankutty_vlogs', 'Sekhar santhosh', 'https://www.instagram.com/sekharankutty_vlogs/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'review', 'unboxing', 'finds']::text[], 15000, 'Enthusiasts/general', 'Bangalore', '+917902828625', '1516/A 3rd floor 26th main road, BDA layout , HSR layout, Bangalore, Karnataka, 560102', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b9577a1e5d20a22e'),
('IN314', 'pgxpitstop', NULL, 'https://www.instagram.com/pgxpitstop/', 'instagram', 'nano', ARRAY['auto', 'toys', 'rc']::text[], 15000, 'Enthusiasts', 'Delhi', '+919891224832', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f99de0e59f24457c'),
('IN315', 'car.crazy.guy', 'Vipul Punetha', 'https://www.instagram.com/car.crazy.guy/reels/', 'instagram', 'macro', ARRAY['auto', 'rc', 'diecast', 'review']::text[], 200000, 'Enthusiasts', NULL, '+917506781151', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-89d400a10a6ec26c'),
('IN316', 'rahulkollamvlog', 'Rahul', 'https://www.instagram.com/rahulkollamvlog/', 'instagram', 'nano', ARRAY['vlogs', 'review', 'finds', 'tech']::text[], 30000, 'general', NULL, '+919536958422', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d8bdd9b11d69ce91'),
('IN317', 'santhoshsuperstoresannanagar', NULL, 'https://www.instagram.com/santhoshsuperstoresannanagar/', 'instagram', 'nano', ARRAY['rc', 'toys', 'diecast']::text[], 2000, 'general/kids', NULL, '+919500012395', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-79c1687feabb7c11'),
('IN318', 'zingz_kochi', 'Ahammad', 'https://www.instagram.com/zingz_kochi/', 'instagram', 'nano', ARRAY['review', 'rc', 'toys', 'diecast']::text[], 4500, 'Enthusiasts', 'Kochi', '+85906850998129490085', 'Zingz & kr tech, St. Antony''s Building, Marottichuvad Junction, Edappally, Ernakulam, Kerala - 682024', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3a150cdb44bee84f'),
('IN319', 'sage.vloh', NULL, 'https://www.instagram.com/p/DOBPFBhkosi/', 'instagram', 'nano', ARRAY['vlogs', 'review']::text[], 20000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f26f5e3c6c1e9e53'),
('IN320', 'erobo.me', NULL, 'https://www.instagram.com/erobo.me/', 'instagram', 'macro', ARRAY['review', 'rc', 'tech', 'diecast']::text[], 30000, 'Enthusiasts/general', 'Kodungallur', '+917558022255', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f77d8b22f9521e6f')
ON CONFLICT (influencer_code) DO NOTHING;
