-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN121', 'tokyoo.in', NULL, 'https://www.instagram.com/tokyoo.inc/', 'instagram', 'micro', ARRAY['rc', 'toys']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f517703361fc7c84'),
('IN122', 'bentotoysblr', NULL, 'https://www.instagram.com/bentotoysblr/', 'instagram', 'nano', ARRAY['rc', 'toys']::text[], 2000, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-791b7faa83c871b7'),
('IN123', 'wikkified', NULL, 'https://www.instagram.com/wikkified/', 'instagram', 'micro', ARRAY['vlogs']::text[], 60000, 'General', 'Chennai', '+919080919124', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-54e9c62df5e121c8'),
('IN124', 'sr_gadgets_kerala', NULL, 'https://www.instagram.com/sr_gadgets_kerala/', 'instagram', 'macro', ARRAY['finds', 'review']::text[], 200000, 'Adults', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-fe9a40eed36c4987'),
('IN125', 'toycollectorsindia', NULL, 'https://www.instagram.com/toycollectorsindia/', 'instagram', 'micro', ARRAY['toys']::text[], 15000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-62313ec0b1d3a892'),
('IN126', 'happyhomes.retail', NULL, 'https://www.instagram.com/happyhomes.retail/', 'instagram', 'macro', ARRAY['toys']::text[], 70000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-925483106e2a6027'),
('IN127', 'hotwheels_malayalam', NULL, 'https://www.instagram.com/hotwheels_malayalam/', 'instagram', 'nano', ARRAY['toys']::text[], 30000, 'Mix', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9ede8ec142fc0317'),
('IN128', 'shop.yourflowers', NULL, 'https://www.instagram.com/shop.yourflowers/', 'instagram', 'nano', ARRAY['toys']::text[], 10000, 'Women', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-03f66b2fd55512a0'),
('IN129', 'dheepan_cars', NULL, 'https://www.instagram.com/dheepan_cars/', 'instagram', 'nano', ARRAY['rc', 'toys']::text[], 12000, 'Enthusiasts', NULL, '+919788775191', NULL, NULL, NULL, 'Manager', NULL, 'master', 'omnipres-inf-e6b0112fa794d4d7'),
('IN130', '_travelling_diary_karnataka', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6f9c89d6673c90f5'),
('IN131', 'cbe_eventz', NULL, 'https://www.instagram.com/cbe_eventz/', 'instagram', NULL, NULL, 50000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-91c0f7091249391c'),
('IN132', 'rccar.arena', NULL, 'https://www.instagram.com/rccar.arena/', 'instagram', NULL, NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-daa52eb4ecbc9ff3'),
('IN133', 'Nithin', NULL, 'https://www.youtube.com/c/sainithintech', 'youtube', 'macro', ARRAY['tech']::text[], 30000, NULL, NULL, '+917013524081', NULL, 'businesswithnithin2@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9c448093c8858a72'),
('IN134', 'thekurtaguy', NULL, 'https://www.instagram.com/thekurtaguy/', 'instagram', 'macro', ARRAY['vlogs']::text[], 500000, 'General', NULL, '+919538390897', NULL, 'vividh@clout.pocketaces.in', NULL, 'Manager', NULL, 'master', 'omnipres-inf-c7e923793a3b2889'),
('IN135', 'thesortedgirl', NULL, 'https://www.instagram.com/thesortedgirl/', 'instagram', 'micro', ARRAY['vlogs']::text[], 50000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b86570457980bb52'),
('IN136', 'therouteandrogue', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-73710fe3c79565a4'),
('IN137', 'thinktravelfood', NULL, 'https://www.instagram.com/thinktravelfood/', 'instagram', 'macro', ARRAY['review', 'finds']::text[], 150000, 'Mix', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6c10b1b477cf0f4c'),
('IN138', 'cassiusclydepereira', 'Cassy Pereira', 'https://www.instagram.com/cassiusclydepereira/', 'instagram', 'micro', ARRAY['vlogs', 'finds']::text[], 400000, 'General', NULL, '+919611109360', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-eb5ac47b2520135f'),
('IN139', 'arjun_photographi', NULL, 'https://www.instagram.com/arjun_photographi/', 'instagram', 'micro', ARRAY['rc']::text[], 80000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-257deeab8169990f'),
('IN140', 'weebsterofficial', NULL, 'https://www.instagram.com/weebsterofficial/', 'instagram', 'nano', ARRAY['diecast']::text[], 3000, 'General', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a20c3166677dbab4'),
('IN141', '_disney._.kids_', NULL, 'https://www.instagram.com/_disney._.kids_/', 'instagram', 'nano', ARRAY['toys', 'rc']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-25363aa69f10416b'),
('IN142', 'diecastviewer', NULL, 'https://www.instagram.com/diecastviewer/', 'instagram', 'nano', ARRAY['diecast']::text[], 2000, 'General', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-45094d535bcadea8'),
('IN143', 'minitoysworldofficial', NULL, 'https://www.instagram.com/minitoysworldofficial/', 'instagram', 'nano', ARRAY['rc', 'diecast']::text[], 3000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-49f676f011c5055e'),
('IN144', 'expertshopy_kohinoor', NULL, 'https://www.instagram.com/expertshopy_kohinoor/', 'instagram', 'nano', ARRAY['diecast', 'rc']::text[], 6000, 'Enthusiasts', NULL, '+918157034363', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-59e0f3becd18639a'),
('IN145', 'drdrive_official', NULL, 'https://www.instagram.com/drdrive_official/', 'instagram', 'micro', ARRAY['auto']::text[], 40000, 'Adults', NULL, '+917907937286', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f7720d2c5d3ee43e'),
('IN146', 'tinytoystown', NULL, 'https://www.instagram.com/tinytoystown/reels/', 'instagram', 'nano', ARRAY['diecast']::text[], 12000, 'Enthusiasts', NULL, '+919995904077', 'Balu Mohan S Peach -14D, SFS Cyber Palms, NH bypass, Karimanal, Kulathoor THIRUVANANTHAPURAM, KERALA 695583 India 9995904077, 6282640788', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3febc970f3480dfb'),
('IN147', 'hotwheels_kochiii', NULL, 'https://www.instagram.com/hotwheels_kochiii/', 'instagram', 'nano', ARRAY['diecast']::text[], 4000, 'Enthusiasts', NULL, '+917012442502', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5d10344756029422'),
('IN148', 'Varun', NULL, 'https://www.instagram.com/varun__padmanabhan', 'instagram', 'nano', ARRAY['vlogs']::text[], 100000, 'Adults', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-c75258428b2e5145'),
('IN149', 'mr_vishal777_', NULL, 'https://www.instagram.com/mr_vishal777_/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-01fbd0a11788cd8c'),
('IN150', 'Vivek', NULL, 'https://www.instagram.com/vive_dts_/', 'instagram', 'nano', ARRAY['cinematic']::text[], 10000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0f796033c2a020ea'),
('IN151', 'Nishant - Chanda(kid inf)', NULL, 'https://www.instagram.com/nishant_panwar2022/', 'instagram', 'nano', ARRAY['vlogs', 'toys']::text[], 10000, 'Parents/Kids', NULL, '+919636544323', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-184fc317ed64f1b6'),
('IN152', 'Ayansh - Himanshi(kid inf)', NULL, 'https://www.instagram.com/ayansh_vibes/', 'instagram', 'nano', ARRAY['vlogs', 'toys']::text[], 6000, 'Parents/Kids', NULL, '+917355554548', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9f15da083323fd50'),
('IN153', 'kartik sharma', NULL, 'https://www.instagram.com/karti.ksharma2023/', 'instagram', 'micro', ARRAY['toys', 'vlogs']::text[], 10000, 'Parents/Kids', NULL, '+919013515021', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4ef19db30d5ba212'),
('IN154', 'Aparna rajani', NULL, 'https://www.instagram.com/momn_babyblog34/', 'instagram', 'nano', ARRAY['finds', 'unboxing']::text[], 12000, 'General', NULL, '+917574804285', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ecdcb4473067bd45'),
('IN155', 'Younus ahmed', NULL, 'https://www.instagram.com/younusahmed_official', 'instagram', 'micro', ARRAY['vlogs']::text[], 1000000, 'General', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1c765e137bd8bb0e'),
('IN156', 'mallikas.archive', NULL, 'https://www.instagram.com/mallikas.archive/', 'instagram', 'micro', ARRAY['finds', 'review']::text[], 10000, 'Women', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-461d9ef5d2e5984d'),
('IN157', 'alfiyakarimkhan_', NULL, 'https://www.instagram.com/alfiyakarimkhan_/', 'instagram', 'micro', ARRAY['review', 'finds']::text[], 250000, 'Women', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cf19467d076d572d'),
('IN158', 'astroplhileet', NULL, 'https://www.instagram.com/astroplhileet/', 'instagram', 'micro', ARRAY['finds', 'vlogs']::text[], 100000, 'Women', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0c8758eb4a8dbaf0'),
('IN159', 'herfabway', NULL, 'https://www.instagram.com/herfabway/', 'instagram', 'micro', ARRAY['finds', 'review', 'unboxing']::text[], 1000000, 'General', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6d186298e2ef3bd5'),
('IN160', 'Vaibhav', NULL, 'https://www.instagram.com/vaibhavsisinty/', 'instagram', 'macro', ARRAY['tech']::text[], 400000, 'General', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ed2b65abaff76dd2')
ON CONFLICT (influencer_code) DO NOTHING;
