-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN361', 'candidgadgets', NULL, 'https://www.instagram.com/candidgadgets/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'review', 'unboxing']::text[], 15000, 'enthusiasts', NULL, '+919342718636', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-15422b2f91e076b5'),
('IN362', 'voiceofmallu', 'Jishnu B S Athiyanoor', 'https://www.instagram.com/voiceofmallu/', 'instagram', 'nano', ARRAY['vlogs', 'diecast']::text[], 15000, 'general', NULL, '+919633669640', 'Mundaplavila veedu arangamukal aralummoodu po 695123 trivandrum kerala', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4414a508e54afab9'),
('IN363', 'toylanddelhi', NULL, 'https://www.instagram.com/toylanddelhi/', 'instagram', 'macro', ARRAY['review', 'rc', 'toys', 'diecast']::text[], 60000, 'kids/enthusiasts', 'Chandi Chowk, Tilak Nagar, Delhi', '+99997868709891449177', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0e11a963327da2f4'),
('IN364', 'toytrackshop', NULL, 'https://www.instagram.com/toytrackshop/', 'instagram', 'nano', ARRAY['toys', 'rc', 'review', 'diecast']::text[], 30000, 'kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-649b5d53fe2b9b9b'),
('IN365', 'nostu_vibez', NULL, 'https://www.instagram.com/nostu_vibez/', 'instagram', 'nano', ARRAY['diecast', 'review']::text[], 2500, 'enthusiasts', 'Trivandrum', NULL, 'Ph : 9633669640', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-1ed1d1bd0f476ebd'),
('IN366', 'badhabits.official', NULL, 'https://www.instagram.com/badhabits.official/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], 6000, 'gifting/general', 'Bangalore, hyderabad', '+919480605990', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e5dad135505f8ef4'),
('IN367', 'kunjuvandikaran', 'Saran Raj S', 'https://www.instagram.com/kunjuvandikaran/', 'instagram', 'nano', ARRAY['diecast', 'tech']::text[], 3500, 'art lovers/enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-71e061e8682d6c1e'),
('IN368', 'alameenskr', 'Alameen Skr', 'https://www.instagram.com/alameenskr/', 'instagram', 'nano', ARRAY['vlogs']::text[], 20000, 'general', 'Trivandrum', '+919037600600', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-35a4d31dab1465b7'),
('IN369', 'toyfort', NULL, 'https://www.instagram.com/toyfort/', 'instagram', 'micro', ARRAY['toys', 'diecast', 'rc', 'review', 'unboxing']::text[], 10000, 'kids/Parents', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-30e062f4e62afc3f'),
('IN370', 'evojet_wheels', 'Muhammed Naimsha', 'https://www.instagram.com/evojet_wheels/', 'instagram', 'nano', ARRAY['diecast', 'cinematic', 'tech']::text[], 18000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-61beace6f0a459dd'),
('IN371', 'r_u_s_t_e_d__n_u_t', 'Manuprasad', 'https://www.instagram.com/r_u_s_t_e_d__n_u_t/', 'instagram', 'nano', ARRAY['diecast', 'auto']::text[], 15000, 'enthusiasts', NULL, '+918667327312', 'Manuprasad MPR 21/B, First Floor, Mythripuram Colony, Thrikkakara, Ernakulam, Kerala 682021Ph: 866 732 7312', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-10038888d1843ebe'),
('IN372', '____buttercupxx____', 'Helen', 'https://www.instagram.com/____buttercupxx____/', 'instagram', 'nano', ARRAY['vlogs', 'diecast']::text[], 30000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-937d5311f4862688'),
('IN373', 'mini.garage164', NULL, 'https://www.instagram.com/mini.garage164/reels/', 'instagram', 'micro', ARRAY['diecast', 'unboxing', 'rc', 'cinematic']::text[], 10000, 'enthusiasts', NULL, '+919182451567', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ef34d8d89dddd2ac'),
('IN374', 'toystorey.in', NULL, 'https://www.instagram.com/toystorey.in/', 'instagram', 'macro', ARRAY['rc', 'diecast', 'toys', 'review']::text[], 15000, 'kids/enthusiasts', 'Coimbatore', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cee32e7ba5f64f41'),
('IN375', 'havochobbybangalore_rc', NULL, 'https://www.instagram.com/havochobbybangalore_rc/reels/', 'instagram', 'micro', ARRAY['rc', 'diecast', 'review', 'unboxing', 'toys']::text[], 20000, 'enthusiasts', 'Bangalore', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-99631cc075bc8238'),
('IN376', 'tech_kalki', 'Kalki', 'https://www.instagram.com/tech_kalki/', 'instagram', 'macro', ARRAY['tech', 'rc', 'review']::text[], 90000, 'enthusiasts', NULL, NULL, NULL, 'techkalki01@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-7ff0b1937cf419be'),
('IN377', 'toys4bacha_kerala', NULL, 'https://www.instagram.com/toys4bacha_kerala/reels/', 'instagram', 'micro', ARRAY['rc', 'toys', 'diecast', 'review', 'unboxing']::text[], 10000, 'Enthusiasts/kids', 'Kerala', '+81119478649645217893', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-48e738b416594fb3'),
('IN378', 'v_r_toys', NULL, 'https://www.instagram.com/v_r_toys/', 'instagram', 'nano', ARRAY['rc', 'toys', 'diecast', 'review']::text[], 10000, 'kids/enthusiasts', 'Indore', '+919425963588', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-87205e0a499dc1f6'),
('IN379', 'indiandiecast', NULL, 'https://www.instagram.com/indiandiecast/', 'instagram', 'nano', ARRAY['diecast', 'review', 'unboxing']::text[], 6000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4bcdbec465d19dff'),
('IN380', 'bee_gifts_house_', 'Abinaya Murali', 'https://www.instagram.com/bee_gifts_house_/', 'instagram', 'micro', ARRAY['vlogs', 'diecast']::text[], 15000, 'gifting', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e8595e86c57a4220'),
('IN381', 'drones_of_chennai', NULL, 'https://www.instagram.com/drones_of_chennai/', 'instagram', 'nano', ARRAY['rc', 'diecast', 'unboxing', 'review', 'toys']::text[], 10000, 'Enthusiasts/kids', 'Chennai', '+97910572038939112294', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-71b97c921fc45b53'),
('IN382', 'decorstation_store', NULL, 'https://www.instagram.com/decorstation_store/reels/', 'instagram', 'nano', ARRAY['diecast', 'rc', 'toys', 'review']::text[], 5000, 'Enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3d11478ecce893f3'),
('IN383', 'mrb_home_decor_mall_official', NULL, 'https://www.instagram.com/mrb_home_decor_mall_official/', 'instagram', 'macro', ARRAY['diecast']::text[], 100000, 'enthusiasts/decor', 'Ahmedabad', '+917900842235', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-429123af4eb4f35e'),
('IN384', 'tech_catcher_official', 'Govinda raj', 'https://www.instagram.com/tech_catcher_official/', 'instagram', 'macro', ARRAY['tech', 'review']::text[], 250000, 'enthusiasts', NULL, '+77361922119995642449', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-29d3258b546f5445'),
('IN385', 'kamarnibnu', NULL, 'https://www.instagram.com/kamarnibnu/', 'instagram', 'micro', ARRAY['tech', 'rc', 'diecast', 'review', 'auto', 'cinematic']::text[], 30000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-10ebba4912c53357'),
('IN386', 'theeporidiecast', NULL, 'https://www.instagram.com/theeporidiecast/', 'instagram', 'micro', ARRAY['diecast', 'review', 'cinematic', 'unboxing', 'rc']::text[], 30000, 'enthusiasts', NULL, '+919633499455', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-30568ef3e30faaed'),
('IN387', 'partybasket.store', NULL, 'https://www.instagram.com/partybasket.store/', 'instagram', 'nano', ARRAY['diecast', 'toys', 'rc']::text[], 1500, 'women/gifting', 'Bhubaneshwar', '+917205404518', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-99fbc34117e7f4aa'),
('IN388', 'gurprinceofficial', NULL, 'https://www.instagram.com/gurprinceofficial/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-798669235fd68275'),
('IN389', 'khushiiiiix.__', 'Khushi', 'https://www.instagram.com/khushiiiiix.__/', 'instagram', 'nano', ARRAY['vlogs', 'diecast']::text[], 20000, 'general', 'Mumbai', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-01dad592de827adc'),
('IN390', 'techy_vicky', 'VIKNESHWARAN KUMARAGURU', 'https://www.instagram.com/techy_vicky/', 'instagram', 'nano', ARRAY['diecast', 'tech', 'auto', 'review', 'unboxing']::text[], 5000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-77a6e1cab78a0e9c'),
('IN391', 'SanuTech', NULL, 'https://www.youtube.com/@SanuTech/shorts', 'youtube', 'macro', ARRAY['rc', 'unboxing', 'review']::text[], 30000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-99c5eff8c8118834'),
('IN392', 'Bossrajput561', NULL, 'https://www.youtube.com/@Bossrajput561/shorts', 'youtube', 'macro', ARRAY['rc', 'toys', 'review', 'unboxing']::text[], 50000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-82bfcee41c64c7c3'),
('IN393', 'AmanModelMaker', 'Aman', 'https://www.youtube.com/@AmanModelMaker', 'youtube', 'macro', ARRAY['tech', 'rc', 'review']::text[], 90000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b4792fe50b743dc5'),
('IN394', 'TotalToys1', NULL, 'https://www.youtube.com/@TotalToys1', 'youtube', 'micro', ARRAY['rc', 'review', 'unboxing', 'toys']::text[], 25000, 'Enthusiasts/kids', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-ee268b27745d3ad7'),
('IN395', 'Amanaktoy', NULL, 'https://www.youtube.com/@Amanaktoy', 'youtube', 'nano', ARRAY['rc', 'unboxing', 'review', 'cinematic']::text[], 15000, 'enthusiasts', NULL, NULL, NULL, 'amanya9153@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-4f086cec2aecc678'),
('IN396', 'vishalcreator19', 'Vishal', 'https://www.youtube.com/@vishalcreator19', 'youtube', 'nano', ARRAY['review', 'unboxing', 'rc', 'toys']::text[], 20000, 'Enthusiasts/kids', NULL, NULL, NULL, 'aahan9799@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-6b2a8f645acacd4d'),
('IN397', 'gauthamsays', 'Gautham', 'https://www.instagram.com/gauthamsays/', 'instagram', 'macro', ARRAY['vlogs', 'review']::text[], 50000, 'general', NULL, '+919150852713', 'No 36 alikhan street alandur chennai - 600016', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-576783a1744185fe'),
('IN398', 'natkhatBoy001', NULL, 'https://www.youtube.com/@natkhatBoy001', 'youtube', 'macro', ARRAY['review', 'rc', 'cinematic']::text[], 15000, 'enthusiasts', NULL, NULL, NULL, 'riteshgg9219@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-ae80964ef18757e2'),
('IN399', 'Game3DKing', 'Amit', 'https://www.youtube.com/@Game3DKing', 'youtube', 'nano', ARRAY['rc', 'review']::text[], 3000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b61c335d776f774a'),
('IN400', '21brandedboy', 'Jason', 'https://www.youtube.com/@21brandedboy', 'youtube', 'nano', ARRAY['review', 'tech', 'rc', 'auto']::text[], 20000, 'enthusiasts', NULL, NULL, NULL, 'heybrandedboy@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-9284cd58bf7ff412')
ON CONFLICT (influencer_code) DO NOTHING;
