-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN721', 'spidy_machan', NULL, 'https://www.instagram.com/spidy_machan/', 'instagram', NULL, NULL, 200000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8bc01dcf21a55049'),
('IN722', 'hancybox', 'Suhail ahmed', 'https://www.instagram.com/hancybox/reels/', 'instagram', NULL, NULL, 100000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-fd67fce10b4d8097'),
('IN723', '8800_mad_rider', NULL, 'https://www.instagram.com/8800_mad_rider/reels/', 'instagram', 'micro', NULL, 25000, 'automotive content', 'Kerala', '+918281107425', 'Muthirakkalayil House Pezhakkappilly P.O Muvattupuzha Ernakulam 686673', 'ikigaicustoms8800@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-ce981b6f06fbfa87'),
('IN724', 'justcouplevibes_', 'Garima Yadav', 'https://www.instagram.com/justcouplevibes_/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 15000, 'general content', 'Pune', '+917718819234', 'A-1001, Beverly Hills society near Rahul international school, Hinjewadi phase-1, pune -411057', 'garimagnit@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-9663acca639889ab'),
('IN725', 'fave.finds.blr', NULL, 'https://www.instagram.com/fave.finds.blr/reels/', 'instagram', NULL, NULL, 100000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8f29426a03d5c1b2'),
('IN726', 'naimatnagaria', NULL, 'https://www.instagram.com/naimatnagaria/reels/', 'instagram', NULL, NULL, 800000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-4a69b65b30885f99'),
('IN727', 'rayhaanmayhem', 'Rayhaan Shaik', 'https://www.instagram.com/rayhaanmayhem/', 'instagram', NULL, NULL, 200000, NULL, 'Bengaluru', '+919791544287', 'BG003, Ground floor, VSPL gardenia, 118, Pemme Gowda Rd, Anjenappa Block, Benson Town, Bengaluru, Karnataka 560046', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-91c8ccc63970c898'),
('IN728', 'benhur_rider46', 'Oddi Benhur', 'https://www.instagram.com/benhur_rider46/reels/', 'instagram', NULL, NULL, 1000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-322a83a2a875b64b'),
('IN729', 'autizmen', NULL, 'https://www.instagram.com/autizmen/', 'instagram', 'micro', NULL, 1000000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-28a672a049505b2d'),
('IN730', 'akanksha_malde', 'Akanksha V Malde', 'https://www.instagram.com/akanksha_malde/', 'instagram', 'nano', ARRAY['ugc']::text[], 10000, 'general content', 'Bengaluru', '+919480972005', 'B1,#26,Sneha Pallavi Apartments,  6th main road,  Meenakshi Nagar,  Basaveshwaranagar,  Bengaluru 560079', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-4bfce9789d959df2'),
('IN731', 'vibrant_lifestyle_', 'Shaurya', 'https://www.instagram.com/vibrant_lifestyle_/reels/', 'instagram', 'nano', ARRAY['ugc']::text[], NULL, NULL, NULL, '+919967690782', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-47de6681505b1c07'),
('IN732', 'harshieesthetic', 'Harshita', 'https://www.instagram.com/harshieesthetic/', 'instagram', 'nano', ARRAY['ugc']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-67bb1697957604ae'),
('IN733', 'dikshakarmyal', NULL, 'https://www.instagram.com/dikshakarmyal/', 'instagram', 'nano', ARRAY['ugc']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-662616662ed2754c'),
('IN734', 'beauteabalance', 'Suhasi', 'https://www.instagram.com/beauteabalance/', 'instagram', 'nano', ARRAY['ugc']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2dad870c832507e1'),
('IN735', 'ugcwithdivaa', 'Divya', 'https://www.instagram.com/ugcwithdivaa/', 'instagram', 'nano', ARRAY['ugc']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-aff1eb015668ab48'),
('IN737', 'bharath_madmix', 'Bharath', 'https://www.instagram.com/bharath_madmix/reels/', 'instagram', 'macro', ARRAY['tech']::text[], NULL, NULL, 'Bengaluru', '+919380555395', 'mysore road new gudadhahali near rain tree school banglore 26 karnataka 560026', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-6e3ab59ba518cc61'),
('IN738', 'krisha_advani', 'Krisha Advani', 'https://www.instagram.com/krisha_advani/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-a6c8b7932d8cb613'),
('IN739', 'kuaurek', 'Kuhoo Kaushik & Ekum Sachdeva', 'https://www.instagram.com/kuaurek/reels/', 'instagram', 'micro', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-5f52de8e928e49fd'),
('IN740', 'that_dcguy', NULL, 'https://www.instagram.com/that_dcguy/reels/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-77465ac313ea74e7'),
('IN741', 'pallavi__nagaraj_', NULL, 'https://www.instagram.com/pallavi__nagaraj_/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-97be1d8122e4e730'),
('IN742', 'vanyaandmom', NULL, 'https://www.instagram.com/vanyaandmom/reels/', 'instagram', 'micro', ARRAY['finds', 'review', 'vlogs']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0cc2e23d5e768fb1'),
('IN743', 'dctinygarage', NULL, 'https://www.instagram.com/dctinygarage/reels/', 'instagram', 'nano', ARRAY['diecast', 'toys']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-8960c6e0558f3244'),
('IN744', 'oldpistons', NULL, 'https://www.instagram.com/oldpistons/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-67dbc4488a6b5dfd'),
('IN745', 'mrunal.shankar', 'Mrunal Nair', 'https://www.instagram.com/mrunal.shankar/reels/', 'instagram', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2b63657513358b78'),
('IN746', 'gireesh_techy', NULL, 'https://www.instagram.com/gireesh_techy/', 'instagram', 'macro', ARRAY['tech']::text[], 30000, 'tech content', 'Kerala', '+918129140388', 'Mens PG Kaypilli Road, Kaloor, Ernakulam, Kerala 682017', NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3c98c0f1e45f0ed7'),
('IN747', 'ksntalks', 'Kishan Sharma', 'https://www.instagram.com/ksntalks/', 'instagram', 'nano', NULL, 5000, 'Automotive content', 'New Delhi', '+919354263022', '99 B Om Vihar Phase 2, Uttam Nagar West, New Delhi - 110059 Landmark - Near SBI ATM', 'Ksntalks@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-e17dff8639a3752b'),
('IN748', 'techymuzaffar', 'Muzaffar Hussain', 'https://www.instagram.com/techymuzaffar/', 'instagram', 'macro', ARRAY['review', 'tech', 'finds', 'toys']::text[], 25000, 'tech content', 'New Delhi', '+919354540793', 'R-87 Street NO 8 Joga Bai Extn Okhla New Delhi 110025', 'techymuzaffarbusiness@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-0880d91ee972ab66'),
('IN749', 'crazy_cars_chennai', 'AK Mathivanan', 'https://www.instagram.com/crazy_cars_chennai/', 'instagram', 'micro', NULL, 25000, 'car content', 'Tamil Nadu', '+917339322611', 'Room no 307, NCM Palace, Sydoji street, Triplicane, Chennai 600005', 'akmathi9797@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-5b4ac8aaf0ddd4c0'),
('IN750', 'the.nalayak_', 'Rishikesh Tripathi', 'https://www.instagram.com/the.nalayak_/', 'instagram', 'macro', ARRAY['vlogs']::text[], 50000, 'general content', 'Madhya Pradesh', '+917000036711', '00514, Indraprasth Nagar, Ward No 1, In front of Baba Kirana Store, Sidhi, Madhya Pradesh 486661', 'nalayakhokya@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-53ca403adcd8047e'),
('IN751', 'diiipanjan', 'Dipanjan Biswas', 'https://www.instagram.com/diiipanjan/', 'instagram', 'nano', ARRAY['vlogs']::text[], 30000, 'travel/bike content', 'Assam', '+918473807700', 'Biswanath chariali Ambari madhyampara ward number 3, 784176', 'biswasaniket666@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-8ae15cd64ece184a'),
('IN752', 'acarautomotive', 'Abhishek', 'https://www.instagram.com/acarautomotive/', 'instagram', 'micro', NULL, 8000, 'Automotive content', 'Mumbai', '+919619830125', 'E/203 Om Shakti building New Panvel near kashinath Annapurna mandir Pali devad sukapur PIN 410206', 'abhishekkalsulkar30@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-001561b2195c89c7'),
('IN753', 'sritechinfo_kannada', 'Srikanth', 'https://www.instagram.com/sritechinfo_kannada/', 'instagram', 'macro', ARRAY['vlogs']::text[], 30000, 'general content', 'Karnataka', '+916363614443', 'PM6X+CC7, Bhovi Colony, Vinayaka Nagar, Anekal, Karnataka 562106, Bengaluru, 562106', 'srikanthsrikanthv94@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-d2a5532c9724f568'),
('IN754', 'nehaharsora_', 'Neha', 'https://www.instagram.com/nehaharsora_', 'instagram', 'macro', ARRAY['ugc']::text[], 500000, 'UGC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-0275f0259e6cef8c'),
('IN755', 'voxpop.bangalore', NULL, 'https://www.instagram.com/voxpop.bangalore/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], 150000, 'random content', 'Karnataka', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f62b550934558790'),
('IN756', 'maskmantoys', NULL, 'https://www.instagram.com/maskmantoys/reels/', 'instagram', 'macro', ARRAY['toys', 'tech']::text[], 200000, 'Toys/gadgets', 'Delhi', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-b34919664aec8e83'),
('IN757', 'thesouthsideshow', NULL, 'https://www.instagram.com/thesouthsideshow', 'instagram', 'nano', ARRAY['vlogs']::text[], 100000, 'Random content', 'Karnataka', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d90f9cbff5eda933'),
('IN758', 'hey.dumbo', NULL, 'https://www.instagram.com/hey.dumbo/', 'instagram', 'micro', ARRAY['vlogs']::text[], 300000, 'general content', 'Karnataka', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-24e85acb17763136'),
('IN759', 'hellominiverse', NULL, 'https://www.instagram.com/hellominiverse', 'instagram', 'macro', NULL, 1000000, 'art', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-76829444af30d8f5'),
('IN760', 'digis414', 'Deepak Goel', 'https://www.instagram.com/digis414/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 30000, 'digital snan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-3751cefb67919245'),
('IN761', 'pooodup', 'Poorav', 'https://www.instagram.com/pooodup/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 150000, 'Random content', 'Karnataka', NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-d572dea00b88b193')
ON CONFLICT (influencer_code) DO NOTHING;
