-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN41', 'Ashwin', NULL, 'https://www.instagram.com/hey.digitalsphere/', 'instagram', 'micro', ARRAY['review']::text[], 15000, 'Adults', NULL, NULL, NULL, 'digitalspheret@nexmedia.in', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1fa5231133738d73'),
('IN42', 'Shivani', NULL, 'https://www.instagram.com/shivanisinghfbd/', 'instagram', 'nano', ARRAY['finds']::text[], 15000, 'Women', NULL, NULL, NULL, 'shivanirohitsinghfbd@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9ed6b65f9de0fa92'),
('IN43', 'Avneesh', NULL, 'https://www.instagram.com/tech.sena02/', 'instagram', 'micro', ARRAY['review']::text[], 150000, 'teenagers', NULL, NULL, NULL, 'avneeshsingh6398@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5b2ac2c36625dbfa'),
('IN44', 'Amar and Smruti', NULL, 'https://www.instagram.com/brainkrupt/', 'instagram', 'micro', ARRAY['review']::text[], 100000, 'Adults', NULL, NULL, NULL, 'brainkrupt@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-940357c5112fa52f'),
('IN45', 'Stuti', NULL, 'https://www.instagram.com/the.quirkartforhome/', 'instagram', 'macro', ARRAY['finds']::text[], 250000, 'Women', NULL, NULL, NULL, 'thequirkartforhome@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-463990bdc403203e'),
('IN46', 'Dhananjay Bhosle', NULL, 'https://www.instagram.com/dhananjay_tech/', 'instagram', 'macro', ARRAY['tech']::text[], 100000, 'General', NULL, NULL, NULL, 'yt.dhananjay@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-216d81f14c3a7566'),
('IN47', 'Naveen', NULL, 'https://www.instagram.com/crazy_dealzone/', 'instagram', 'micro', ARRAY['finds']::text[], 20000, 'General', NULL, NULL, NULL, 'crazy33promotion@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1579b5c49e5a681f'),
('IN48', 'Indori explorer', NULL, 'https://www.instagram.com/indoriexplorertech/', 'instagram', 'macro', ARRAY['review']::text[], 30000, 'General', NULL, NULL, NULL, 'divyanshj0@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-563f8c7460a96839'),
('IN49', 'Praveen', NULL, 'https://www.instagram.com/techstuff01/', 'instagram', 'macro', ARRAY['tech']::text[], 350000, 'Mix', NULL, NULL, NULL, 'Businesstechstuff@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-dfd60db9dbc8e00e'),
('IN50', 'payal', NULL, 'https://www.instagram.com/unboxwithpayu/', 'instagram', 'nano', ARRAY['unboxing']::text[], 10000, 'Women', NULL, NULL, NULL, 'payal.lighthouse@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f0206fe57cb4c7df'),
('IN51', 'pukki', NULL, 'https://www.instagram.com/pukki.official/', 'instagram', 'micro', ARRAY['unboxing', 'review', 'finds']::text[], 60000, 'Women', 'Maharashtra', '+919008252937', '702, Lake Tower, Plot No. 217, Nagar Road, Next to Wageshwar temple, Wagholi Pune, Maharashtra, 412207', 'pukkiofficial22@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1e62f01eb09fd067'),
('IN52', 'palak', NULL, 'https://www.instagram.com/palak_jasujaa/', 'instagram', 'nano', ARRAY['finds']::text[], 7000, 'Women', NULL, NULL, NULL, 'business.palakjasuja@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f6617359c20255f0'),
('IN53', 'Ammara', NULL, 'https://www.instagram.com/preppy.bunnie/', 'instagram', 'nano', ARRAY['unboxing']::text[], 25000, 'Women', NULL, NULL, NULL, 'business.ammara@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-256201c3ecb501df'),
('IN54', 'Rishabh', NULL, 'https://www.instagram.com/tech.on.tips/', 'instagram', 'micro', ARRAY['review']::text[], 45000, 'teenagers', NULL, NULL, NULL, 'techontips@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-838d2040d5ce65c0'),
('IN55', 'Farha', NULL, 'https://www.instagram.com/farhanaaz.fn/', 'instagram', 'micro', ARRAY['finds']::text[], 70000, 'Women', NULL, NULL, NULL, 'farhanaaz.collabs@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b4e1a6983ac396d3'),
('IN56', 'Shruthi', NULL, 'https://www.instagram.com/shruthisvault/', 'instagram', 'micro', ARRAY['review', 'finds']::text[], 15000, 'women', NULL, NULL, NULL, 'Shruthisvault@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6dcf904ee66e9ad2'),
('IN57', 'Shivam', NULL, 'https://www.instagram.com/tech_believers/', 'instagram', 'macro', ARRAY['tech']::text[], 70000, 'Mix', NULL, NULL, NULL, 'Business@techbelievers.in', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-40e1feaf3d356654'),
('IN58', 'Nilesh', NULL, 'https://www.instagram.com/techwithniks/', 'instagram', 'micro', ARRAY['tech']::text[], 100000, 'teenagers', NULL, NULL, NULL, 'nileshpatil02410@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-14a7fc17d88eb4ec'),
('IN59', 'gopal', NULL, 'https://www.instagram.com/techo0n/', 'instagram', 'macro', ARRAY['review', 'tech']::text[], 250000, 'Adults', NULL, '+919716077883', NULL, '𝙩𝙚𝙘𝙝𝙤𝙤𝙣𝙘𝙤𝙡𝙡𝙖𝙗@𝙜𝙢𝙖𝙞𝙡.𝙘𝙤𝙢', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-7a06bc996ddb7185'),
('IN60', 'Jai', NULL, 'https://www.instagram.com/tech_iela/', 'instagram', 'macro', ARRAY['review', 'tech']::text[], 600000, 'Adults', NULL, NULL, NULL, 'jai@techiela.tech', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9eea57f1b98bc679'),
('IN61', 'Harshit', NULL, 'https://www.instagram.com/yantra_verse/', 'instagram', 'macro', ARRAY['tech', 'review']::text[], 800000, 'General', NULL, NULL, NULL, 'hiyvofficial@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f2f4b782ae130155'),
('IN62', 'Ram Patil', NULL, 'https://www.instagram.com/tech0sm/', 'instagram', 'micro', ARRAY['review', 'tech']::text[], 100000, 'General', NULL, NULL, NULL, 'ramtipsandtrick@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9a7ac0ae2805bb7f'),
('IN63', 'Fardeen Agwan', NULL, 'https://www.instagram.com/tech_ain_/', 'instagram', 'micro', ARRAY['review', 'tech']::text[], 65000, 'General', NULL, NULL, NULL, 'techain11@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c9c48c8017eb60b3'),
('IN64', 'Naveen Verma', NULL, 'https://www.instagram.com/crazy_dealzone/', 'instagram', 'micro', ARRAY['finds']::text[], 20000, 'Adults', NULL, NULL, NULL, 'crazy33promotion@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-01df944f24b26df7'),
('IN65', 'Utpal Pandey', NULL, 'https://www.instagram.com/utpalpandeyyt/', 'instagram', 'macro', ARRAY['review', 'tech']::text[], 300000, 'General', NULL, NULL, NULL, 'techreal63@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1a2580019e7e36a0'),
('IN66', 'Ananya', NULL, 'https://www.instagram.com/aforananyaa10/', 'instagram', 'nano', ARRAY['review', 'finds']::text[], 20000, 'women', NULL, NULL, NULL, 'Singhh.ananya28@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5b1ae2e653e4a113'),
('IN67', 'Sachin', NULL, 'https://www.instagram.com/techno___craze/', 'instagram', 'micro', ARRAY['review', 'tech']::text[], 60000, 'Adults', NULL, NULL, NULL, 'contact.technocraze@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-00856d08a8d09580'),
('IN68', 'Vijay Gupta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'fwsbharat@yahoo.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-493557536b5ac8e4'),
('IN69', 'Bindu', NULL, 'https://www.instagram.com/_lets.unbox?igsh=a2pmdXJ2aXFkYXUx&utm_source=qr', 'instagram', 'micro', ARRAY['finds']::text[], 50000, 'women', NULL, NULL, NULL, 'bindukaramsetty@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-77f7445ca58e9e2f'),
('IN70', 'Akash Pal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'technicalsky@nexmedia.in', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0456eebd7acc3c08'),
('IN71', 'nightprash', NULL, 'https://www.instagram.com/nightprash/', 'instagram', 'micro', ARRAY['review', 'tech']::text[], 50000, 'adults', NULL, NULL, NULL, 'workwithnightprash@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-71e06c1d42fb7b40'),
('IN72', 'psychofoodiee', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b3cedfa33117e0b7'),
('IN73', 'Yog Sha', NULL, 'https://www.instagram.com/technoyogy.ai/', 'instagram', 'micro', ARRAY['review', 'tech']::text[], 40000, 'general', 'Jharkhand', '+918409205703', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9d8baf001052de65'),
('IN74', 'tech_spert', NULL, 'https://www.instagram.com/tech_spert/', 'instagram', 'macro', ARRAY['tech']::text[], 300000, 'general', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-2382046acadb561d'),
('IN75', 'Surya', NULL, 'https://www.instagram.com/tech_truth_official/', 'instagram', 'micro', ARRAY['tech']::text[], 30000, NULL, NULL, '+918886506639', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f0779a1aac4082a6'),
('IN76', 'Shivam', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '+916267794553', NULL, NULL, NULL, 'Manager', NULL, 'master', 'omnipres-inf-697a609bed92fd39'),
('IN77', 'Manu Bajaj', NULL, 'https://www.instagram.com/iammanubajaj/', 'instagram', 'macro', ARRAY['tech', 'review']::text[], 200000, 'adults', NULL, '+919992355599', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-12d90d406b4fa72c'),
('IN78', 'Abhishek Sharma', NULL, 'https://www.youtube.com/@rccarsobsession', 'youtube', 'micro', ARRAY['rc']::text[], 5000, NULL, NULL, '+919460568986', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-85915149de5078f3'),
('IN79', 'Yash Sethi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '+919212298000', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-56883b4a4d5fd3b0'),
('IN80', 'tech_lekhi', NULL, 'https://www.instagram.com/tech_lekhi/', 'instagram', 'micro', ARRAY['tech']::text[], 50000, 'mix', NULL, '+918094054344', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-04f1b27cae8a18db')
ON CONFLICT (influencer_code) DO NOTHING;
