-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN81', 'divyam rastogi', NULL, 'https://www.instagram.com/thedivyamrastogi/', 'instagram', 'macro', ARRAY['review', 'tech']::text[], 135000, 'adults', NULL, '+919888451588', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-94a419f40be86082'),
('IN82', 'The Hub Bangalore', NULL, 'https://www.instagram.com/thehubbengaluru/', 'instagram', 'macro', ARRAY['vlogs']::text[], 100000, 'general', 'Bengaluru', NULL, NULL, NULL, NULL, 'Agency', NULL, 'master', 'omnipres-inf-797a9e64289bc820'),
('IN83', 'MrcHobby', NULL, 'Instagram', 'instagram', 'nano', ARRAY['rc']::text[], 3500, NULL, NULL, '+917784093093', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9b62430481682c98'),
('IN84', 'Rohit', NULL, 'https://youtube.com/@infinityrohit369?si=e_zNwmD5mHkzl2Ig', 'youtube', NULL, NULL, 40000, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-66a1ea388a09ff14'),
('IN85', 'tech_boyz_official', NULL, 'https://www.instagram.com/tech_boyz_official/', 'instagram', 'nano', ARRAY['rc']::text[], 12000, 'RC enthusiasts', 'Coimbatore', '+919087090840', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ad8c78084024fd84'),
('IN86', 'kl_42dude_official', 'Hafiz Ahmed', 'https://www.instagram.com/kl_42dude_official/', 'instagram', 'nano', ARRAY['tech', 'auto', 'unboxing', 'review']::text[], 15000, 'enthusiasts', 'KL', '+918547658907', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-64fceedf7acc260d'),
('IN87', 'i_am_noel_shorts', NULL, 'https://www.instagram.com/i_am_noel_shorts/', 'instagram', 'micro', ARRAY['review', 'rc']::text[], 80000, 'RC Enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1a389de39b2e52f9'),
('IN88', 'pavandeee', NULL, 'https://www.instagram.com/pavandeee/', 'instagram', 'micro', ARRAY['review']::text[], 200000, NULL, NULL, NULL, NULL, 'pavan@kalakaaar.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-2f0d884aebac3a19'),
('IN89', 'that_thguy', NULL, 'https://www.instagram.com/that_thguy/', 'instagram', 'nano', ARRAY['rc']::text[], 60000, 'General', NULL, NULL, NULL, 'thatmainguy007@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-369e4170f1b30348'),
('IN90', 'isluhacks', NULL, 'https://www.instagram.com/isluhacks/', 'instagram', 'macro', ARRAY['review', 'rc']::text[], 35000, 'RC Enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-8de1e471a42d8b83'),
('IN91', 'hotdealsbro', NULL, 'https://www.instagram.com/hotdealsbro/', 'instagram', 'nano', ARRAY['finds']::text[], 60000, 'Adults', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-606f88f9bdc84317'),
('IN92', 'techspyy', NULL, 'https://www.instagram.com/techspyy/', 'instagram', 'nano', ARRAY['review', 'tech', 'unboxing']::text[], 6000, 'B list', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d8ba4275ea8ee2f6'),
('IN93', 'sillycorns.media', NULL, 'https://www.instagram.com/sillycorns.media/', 'instagram', 'micro', ARRAY['review', 'finds']::text[], 150000, 'General', NULL, NULL, NULL, 'hello@sillycorns.com', NULL, 'Agency', NULL, 'master', 'omnipres-inf-0c0d8af2ee932913'),
('IN94', 'pearlia.co', NULL, 'https://www.instagram.com/pearlia.co/', 'instagram', 'nano', ARRAY['unboxing', 'finds']::text[], 10000, 'Women', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a2993dffaa6045fe'),
('IN95', '_stylish_krishan', NULL, 'https://www.instagram.com/_stylish_krishan_/', 'instagram', 'micro', ARRAY['review', 'finds']::text[], 250000, 'General', 'Jaipur', NULL, NULL, 'Natthuramsaini08@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-728f8417c4d0554e'),
('IN96', 'maverick_toys', NULL, 'https://www.instagram.com/maverick_toys/', 'instagram', 'nano', ARRAY['rc']::text[], 10000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-913dae8563fd77ca'),
('IN97', 'igarage.in', NULL, 'https://www.instagram.com/igarage.in/', 'instagram', 'micro', ARRAY['rc']::text[], 50000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-34944d44a902cb09'),
('IN98', 'rcanddiecast', NULL, 'https://www.instagram.com/rcanddiecast/', 'instagram', 'nano', ARRAY['rc']::text[], 8000, 'RC enthusiasts', NULL, '+918606447311', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-cd51692b9bbb8c18'),
('IN99', 'hoodieguy98', NULL, 'Instagram', 'instagram', 'macro', ARRAY['unboxing', 'review']::text[], 150000, 'Adults', NULL, '+917845245078', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f8e75ac4024336ee'),
('IN100', 'Bharath Hobby', NULL, 'Instagram', 'instagram', 'micro', ARRAY['rc']::text[], 100000, 'RC enthusiasts', NULL, '+918779521387', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-074da92b5c98e6d7'),
('IN101', 'MD Shaid', NULL, '(14) Tamu Toys - YouTube', 'youtube', 'macro', ARRAY['toys']::text[], 80000, 'Adults/ Parents', NULL, '+918724865328', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-09cc8fdba16e45d1'),
('IN102', 'MrcHobbies', NULL, 'Instagram', 'instagram', 'nano', ARRAY['rc']::text[], 3000, 'RC enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-ce063d4f04207900'),
('IN103', 'The infinity Rohit', NULL, '(14) The Infinity Rohit - YouTube', 'youtube', 'macro', NULL, 32000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9c2320ae2a1b7f0d'),
('IN104', 'tonybenjo_rc_rx', NULL, 'https://www.instagram.com/tonybenjo_rc_rx/', 'instagram', 'macro', ARRAY['rc']::text[], 180000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d6c9191e7ea6371d'),
('IN105', 'officialbrokebrothers', NULL, 'https://www.instagram.com/officialbrokebrothers/', 'instagram', 'macro', NULL, 100000, 'Adults', 'Blr', NULL, NULL, 'hello@spense.money', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-40963d2e096c6626'),
('IN106', 'Sanju kapoor', NULL, NULL, NULL, 'macro', ARRAY['review', 'finds']::text[], 9000, NULL, NULL, '+918287694881', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e2e6d493ffbad14d'),
('IN107', 'Rishi Trupathi babyblogger', NULL, 'https://www.instagram.com/cute_rishi_tripathi1432/#', 'instagram', 'macro', ARRAY['vlogs']::text[], 35000, 'Parents/ Kids', NULL, '+918279993889', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-2ecf269d3e3e77fc'),
('IN108', 'Montu Singh', NULL, 'https://www.instagram.com/rajputmstech#', 'instagram', 'nano', ARRAY['tech']::text[], 1200, 'General', NULL, '+918696975534', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0a956fe6773f40c4'),
('IN109', 'mak_editing', NULL, 'https://www.instagram.com/mak_editing_/#', 'instagram', 'nano', ARRAY['tech']::text[], 2500, 'General', NULL, '+919783328570', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5d4b3a8518f1d6a5'),
('IN110', 'hobbyhaeven07', NULL, 'https://www.instagram.com/hobbyhaven07?igsh=NzVsbDkxZHFseHZo&utm_source=qr', 'instagram', 'nano', ARRAY['rc']::text[], 3000, 'RC Enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-40ffb760db1c93c3'),
('IN111', 'AdvutMee', NULL, 'https://www.youtube.com/@AdvutMee', 'youtube', 'nano', ARRAY['rc', 'toys', 'tech', 'review']::text[], 16000, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-0f5694f284704c7d'),
('IN112', 'Mr. Marque (Riyas)', NULL, 'https://youtube.com/@mr.marque?si=EmGVvi7aCzaToywn', 'youtube', 'nano', ARRAY['rc']::text[], 15000, 'General', NULL, '+918754498038', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-513ed90c9dff2dd3'),
('IN113', 'akhila_mathwe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-de00755d6a26ab9d'),
('IN114', 'prejimon_pradeep', NULL, 'https://www.instagram.com/prejimon_pradeep/', 'instagram', 'micro', ARRAY['auto']::text[], 60000, 'General', NULL, '+917012738776', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-7f20d5cdaa1083b3'),
('IN115', 'karnataktoystore', NULL, 'https://www.instagram.com/karnataktoysstore/', 'instagram', 'nano', ARRAY['toys']::text[], NULL, NULL, NULL, '+919380045638', NULL, NULL, NULL, 'Manager', NULL, 'master', 'omnipres-inf-8b2c3b737838c707'),
('IN116', 'thehopelessgeek', NULL, 'https://www.instagram.com/thehopelessgeek/', 'instagram', 'nano', ARRAY['review', 'finds']::text[], 11000, 'Adults', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f85d6f1baf2a2f3a'),
('IN117', 'rc_motor_hub', NULL, 'https://www.instagram.com/rc_motor_hub/', 'instagram', 'micro', ARRAY['rc', 'toys']::text[], 30000, 'Adults', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-69eee1900e1ac229'),
('IN118', 'zahirmirza', NULL, 'https://www.instagram.com/zahirmirza/', 'instagram', 'nano', ARRAY['finds', 'blogs']::text[], 5000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3bee66389043c2f1'),
('IN119', 'viaana.kids.store', NULL, 'https://www.instagram.com/viaana.kids.store/', 'instagram', 'macro', ARRAY['toys', 'finds']::text[], 10000, 'Women', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-aa420ca41891e821'),
('IN120', 'unboxingbangalore', NULL, 'https://www.instagram.com/unboxingbangalore/', 'instagram', 'macro', ARRAY['finds', 'blogs']::text[], 500000, 'General', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-66745b5bb7cafb6a')
ON CONFLICT (influencer_code) DO NOTHING;
