-- 40 influencer rows
INSERT INTO ignition._stage_influencers (
  influencer_code,
  channel_name,
  person_name,
  channel_link,
  channel_platform,
  influencer_type,
  categories,
  reach,
  audience,
  location,
  contact_number,
  address,
  email,
  contact_poc_type,
  contact_poc_name,
  first_invite_sent_at,
  list_status,
  legacy_sheet_ref
) VALUES
('IN441', 'therajivmakhni', 'Rajiv Makhni', 'https://www.instagram.com/therajivmakhni/reels/', 'instagram', 'brand', ARRAY['review', 'tech']::text[], 400000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-101cb504258759b5'),
('IN442', 'prasadtechinteluguofficial', 'D S V S R A VARAPRASAD', 'https://www.instagram.com/prasadtechinteluguofficial/reels/', 'instagram', 'brand', ARRAY['unboxing', 'review', 'tech']::text[], 1000000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-bd507fffa34f3953'),
('IN443', 'InventionDestroy', 'Rohit Shroff', 'https://www.youtube.com/@InventionDestroy', 'youtube', 'macro', ARRAY['unboxing', 'review', 'tech']::text[], 20000, 'enthusiasts', NULL, NULL, NULL, 'inventiondestroy@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-8631fb9f7637d16f'),
('IN444', 'indianbackpackerofficial', 'Anmol Jaiswal', 'https://www.instagram.com/indianbackpackerofficial/reels/', 'instagram', 'macro', ARRAY['review']::text[], 1000000, 'travel/enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-22f99133e9dc6b1c'),
('IN445', 'yuvas.journal', 'Yuva', 'https://www.instagram.com/yuvas.journal/reels/', 'instagram', 'micro', ARRAY['finds', 'review', 'vlogs']::text[], 300000, 'general/finds', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-f585ed01a7fac06e'),
('IN446', '_.jaaaiii', 'Jai', 'https://www.instagram.com/_.jaaaiii/reels/', 'instagram', 'micro', ARRAY['review', 'cinematic', 'tech', 'vlogs']::text[], 100000, 'enthusiasts', NULL, '+918156987933', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-06b912806189f8b5'),
('IN447', 'sergiusbarretto', 'Sergius Barretto', 'https://www.instagram.com/sergiusbarretto/reels/', 'instagram', 'nano', ARRAY['review', 'tech']::text[], 50000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-e8c84507be4c93df'),
('IN448', 'Mumbai', 'Eric Jason D’souza', 'https://www.instagram.com/ericjasondsouza/reels/', 'instagram', 'nano', ARRAY['diecast', 'vlogs']::text[], 25000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Manager', NULL, 'master', 'omnipres-inf-b590d6aabb5da8f6'),
('IN449', 'BunnyPuniaVideos', 'Bunny Punia', 'https://www.youtube.com/@BunnyPuniaVideos/shorts', 'youtube', 'nano', ARRAY['review', 'tech', 'rc', 'diecast']::text[], 10000, 'enthusiasts', NULL, NULL, NULL, 'bunnypunia@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-2970f372f7ee408a'),
('IN450', 'autoyogiofficial', NULL, 'https://www.instagram.com/autoyogiofficial/reels/', 'instagram', 'brand', ARRAY['review', 'tech']::text[], 100000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-bf4deda5678edd4d'),
('IN451', 'm_a_u_r__', NULL, 'https://www.instagram.com/m_a_u_r__/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 25000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e0943bd6e6b21b2d'),
('IN452', 'crazy_cars_chennai', 'AK Mathivanan', 'https://www.instagram.com/crazy_cars_chennai/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 30000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-69193788e046044c'),
('IN453', 'kaarrdecor', NULL, 'https://www.instagram.com/kaarrdecor/reels/', 'instagram', 'micro', ARRAY['unboxing', 'review', 'rc', 'toys']::text[], 6000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-b032742cdb53044f'),
('IN454', 'huduga_from_bihar', 'Rajan Kumar', 'https://www.instagram.com/huduga_from_bihar/reels/', 'instagram', 'macro', ARRAY['vlogs', 'diecast']::text[], 150000, 'travel/enthusiasts', 'Bangalore', '+917739179542', '1537 4th Main Road, Mariyappanapalya, Rajajinagar, Bangalore, 560021', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9718adc18411b483'),
('IN455', 'generationspeed', NULL, 'https://www.instagram.com/generationspeed/reels/', 'instagram', 'micro', ARRAY['cinematic', 'vlogs', 'diecast', 'rc']::text[], 50000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c30d7ff5f3c7a41f'),
('IN456', 'divyagupta7811', 'Divya Gupta', 'https://www.instagram.com/divyagupta7811/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 1000000, 'general', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-9beffa841dd2abb8'),
('IN457', 'flying__squirrel__', 'Amrithesh', 'https://www.instagram.com/flying__squirrel__/reels/', 'instagram', 'macro', ARRAY['vlogs', 'tech']::text[], 500000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-924ab8afe3211696'),
('IN458', 'cruisingtahoora', 'Tahoora', 'https://www.instagram.com/cruisingtahoora/reels/', 'instagram', 'nano', ARRAY['review', 'vlogs']::text[], 300000, 'enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-55edd66eeabf0fd3'),
('IN459', 'sanjayrao_asr', 'Sanjay Rao', 'https://www.instagram.com/sanjayrao_asr/reels/', 'instagram', 'macro', ARRAY['review', 'vlogs']::text[], 100000, 'enthusiasts', 'BLR', NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-e164e8eff24cc645'),
('IN460', 'krishaccessories_chennai', NULL, 'https://www.instagram.com/krishaccessories_chennai/reels/', 'instagram', 'store', ARRAY['review', 'rc', 'toys', 'diecast']::text[], 100000, 'kids/enthusiasts', 'Chennai', '+893978923704431528828', NULL, NULL, NULL, NULL, NULL, 'master', 'omnipres-inf-2c883b2eff6b4d30'),
('IN461', 'anirudhexplores', 'Ani', 'https://www.instagram.com/anirudhexplores/reels/', 'instagram', 'micro', ARRAY['review', 'vlogs', 'rc', 'unboxing', 'ugc']::text[], 20000, 'enthusiasts', NULL, '+918884851639', NULL, 'explorewithanirudh@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-99036d78c0876b93'),
('IN462', 'va_supercars', 'Vishal Ashwath', 'https://www.instagram.com/va_supercars/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 300000, 'enthusiasts', NULL, NULL, NULL, 'vablacklisted@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-9d3c29c58c57d728'),
('IN463', 'thesharannair', 'Sharan Nair', 'https://www.instagram.com/thesharannair/reels/', 'instagram', 'macro', ARRAY['vlogs']::text[], 300000, 'general/enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Manager', NULL, 'master', 'omnipres-inf-491d420e9989ae54'),
('IN464', 'krishandaish', 'Krish and Aish', 'https://www.instagram.com/krishandaish/reels/', 'instagram', 'brand', ARRAY['vlogs']::text[], 2000000, 'general', NULL, NULL, NULL, 'krishnaish1018@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-bc6a122c3ad14bad'),
('IN465', 'octane_girl', 'Mia Joseph Chirakkekaran', 'https://www.instagram.com/octane_girl/reels/', 'instagram', 'macro', ARRAY['review', 'vlogs', 'diecast']::text[], 2000000, 'enthusiasts', NULL, NULL, NULL, 'octanegirl.collab@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-bb03915f7113cfc5'),
('IN466', 'tannadhaval', 'T A N N A D H A V A L', 'https://www.instagram.com/reel/Cls_BNZgweE/', 'instagram', 'macro', ARRAY['review', 'vlogs', 'rc', 'diecast']::text[], 4000000, 'enthusiasts', 'Gujrat', NULL, NULL, 'imailtannadhaval@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-5e839d7a9e6498ed'),
('IN467', 'arunsmoki', 'arun smoki', 'https://www.instagram.com/arunsmoki/reels/', 'instagram', 'brand', ARRAY['review', 'vlogs']::text[], 1000000, 'enthusiasts', NULL, NULL, NULL, 'arunsmokiii@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-08179a8e7134a867'),
('IN468', 'meghanakanderai', 'Meghana Kanderai', 'https://www.instagram.com/meghanakanderai/reels/', 'instagram', 'nano', ARRAY['vlogs', 'finds', 'review']::text[], 50000, 'general/enthusiasts', 'Bangalore', NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-a58527b8e0313a39'),
('IN469', 'sharadlifestyle01', 'SHARAD SHARMA', 'https://www.instagram.com/sharadlifestyle01/reels/', 'instagram', 'macro', ARRAY['review', 'tech', 'vlogs']::text[], 200000, 'enthusiasts', 'Kota', '+918949228380', 'House number- 29 friends colony borkhera. City- kota. Rajasthan - 324001', 'sharadcollab@gmail.com', NULL, 'Agency', NULL, 'master', 'omnipres-inf-32557af780c1ed96'),
('IN470', 'sandy__611', 'Sandesh Shankar Mhaske', 'https://www.instagram.com/sandy__611/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 80000, 'general', NULL, '+917039323178', '42, Nav nanda apt, Madhukar nagar, cholegaon, Thakurli (East). Pincode - 421201', NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-5a6d5684e0817c74'),
('IN471', 'ux.karsh', 'Utkarsh', 'https://www.instagram.com/ux.karsh/reels/', 'instagram', 'nano', ARRAY['vlogs', 'ugc', 'finds']::text[], 10000, 'UX generic', 'Bangalore', NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-6418bba1a679fa06'),
('IN472', 'the_ravirider', 'Ravindra Singh Shekhawat', 'https://www.instagram.com/the_ravirider/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], 100000, 'enthusiasts', 'Jaipur', '+916378828524', 'Shop no. 3&4 manhori palace near surya nagar rajin hotel benar road nadi ka phatak jhotwara jaipur Rajasthan 302012', 'workwithravirider@gmail.com', NULL, NULL, NULL, 'master', 'omnipres-inf-aad7cb4c94cce78d'),
('IN473', 'me.bonie', 'Bonie', 'https://www.instagram.com/me.bonie/reels/', 'instagram', 'nano', ARRAY['vlogs']::text[], 45000, 'general/enthusiasts', NULL, NULL, NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-d17877338e7b2279'),
('IN474', 'shiva_vs_bike', 'Shiva', 'https://www.instagram.com/shiva_vs_bike/reels/', 'instagram', 'micro', ARRAY['vlogs']::text[], 25000, 'enthusiasts', 'Haryana', '+919350089207', 'h cross, Venkateshwara Hardware (state): Karnataka. City: h cross, Chintamani Road - 562101', 'shivak45256@gmail.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-3a927a50dd2cab2a'),
('IN475', 'houseoftechy', NULL, 'https://www.instagram.com/houseoftechy/reels/', 'instagram', 'nano', ARRAY['unboxing', 'review']::text[], 70000, 'general reviews', NULL, '+919992355599', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-fefb46bef52bda4f'),
('IN476', 'thedriverseatguy', 'Fazil Abbas', 'https://www.instagram.com/thedriverseatguy/reels/', 'instagram', 'macro', ARRAY['review', 'vlogs', 'tech']::text[], 150000, 'enthusiasts', NULL, '+919841632407', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-c31d8aaf2bcd4821'),
('IN477', 'Tech Boss', NULL, 'https://www.youtube.com/@TechBossIndia/videos', 'youtube', 'macro', ARRAY['review', 'tech', 'rc', 'toys', 'finds']::text[], 450000, 'general reviews', 'Tamil Nadu', NULL, NULL, 'techboss@adadacreators.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-314bf7c26547cf6a'),
('IN478', 'therawknee', 'Rony RAWKNEE Dasgupta', 'https://www.youtube.com/channel/UCZaHw7tdjy3TNMH3ncsI4Bg', 'youtube', 'macro', ARRAY['review', 'finds', 'tech', 'toys', 'rc']::text[], 300000, 'reviews/gaming', 'Gujarat', NULL, NULL, 'business@therawknee.com', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f79f25f853fba779'),
('IN479', 'techbar_official', 'Sanchit Shokeen', 'https://www.youtube.com/@TechBar', 'youtube', 'macro', ARRAY['review', 'tech', 'vlogs']::text[], 350000, 'general reviews', 'Delhi', NULL, NULL, 'sanchit@techbar.in', NULL, 'Influencer', NULL, 'master', 'omnipres-inf-1680f7f65f69faf0'),
('IN480', 'sukrith_komarshetty', 'Sunitha komarshetty', 'https://www.instagram.com/sukrith_komarshetty/', 'instagram', 'micro', ARRAY['ugc', 'toys', 'vlogs', 'finds']::text[], 250000, 'general reviews', 'Pune', '+919032233445', NULL, NULL, NULL, 'Influencer', NULL, 'master', 'omnipres-inf-f64748ded1f697a9')
ON CONFLICT (influencer_code) DO NOTHING;
