// All 8 intake request types with their template fields
// used by the New Request form to render the correct template

export const REQUEST_TYPES = [
  { value: 'social',      label: 'Social Content',     icon: '📱' },
  { value: 'campaign',    label: 'Campaign',            icon: '🎯' },
  { value: 'design',      label: 'Design Asset',        icon: '🎨' },
  { value: 'copy',        label: 'Copy / Content',      icon: '✍️' },
  { value: 'photo_video', label: 'Photo / Video Shoot', icon: '📷' },
  { value: '3d',          label: '3D / Motion',         icon: '🎬' },
  { value: 'deck',        label: 'Deck / Presentation', icon: '📊' },
  { value: 'ad',          label: 'Ad Creative',         icon: '📣' },
];

// Template fields per request type
// Each field: { key, label, type, required, options?, placeholder?, conditional? }
export const REQUEST_TEMPLATES = {

  social: [
    { key: 'platforms', label: 'Platform(s)', type: 'multiselect', required: true,
      options: ['Instagram', 'LinkedIn', 'TikTok', 'X', 'YouTube', 'Other'] },
    { key: 'format', label: 'Content Format', type: 'select', required: true,
      options: ['Static', 'Carousel', 'Story', 'Reel', 'Video'] },
    { key: 'dimensions', label: 'Dimensions / Specs', type: 'text', required: true,
      placeholder: 'e.g. 1080×1080px, 9:16 vertical' },
    { key: 'caption_needed', label: 'Caption Required?', type: 'yesno', required: true },
    { key: 'post_date', label: 'Desired Post Date', type: 'date', required: true },
    { key: 'reference_links', label: 'Reference Links / Inspiration', type: 'text', required: false,
      placeholder: 'Paste URLs separated by commas' },
    { key: 'campaign_context', label: 'Campaign or Context', type: 'textarea', required: false },
    { key: 'notes', label: 'Additional Notes', type: 'textarea', required: false },
  ],

  campaign: [
    { key: 'campaign_name', label: 'Campaign Name', type: 'text', required: true },
    { key: 'objective', label: 'Campaign Objective', type: 'textarea', required: true,
      placeholder: 'What is this campaign trying to achieve?' },
    { key: 'channels', label: 'Channels', type: 'multiselect', required: true,
      options: ['Instagram', 'LinkedIn', 'TikTok', 'X', 'YouTube', 'Email', 'Paid Media', 'Print', 'Other'] },
    { key: 'deliverables', label: 'Deliverables List', type: 'textarea', required: true,
      placeholder: 'List each deliverable on a new line' },
    { key: 'launch_date', label: 'Launch Date', type: 'date', required: true },
    { key: 'target_audience', label: 'Target Audience', type: 'text', required: true },
    { key: 'budget_context', label: 'Budget Context', type: 'text', required: false },
    { key: 'reference', label: 'Reference / Mood', type: 'text', required: false,
      placeholder: 'URL or describe the look and feel' },
    { key: 'brief', label: 'Brief Document Link', type: 'text', required: false,
      placeholder: 'Link to brief doc or Drive folder' },
  ],

  design: [
    { key: 'asset_type', label: 'Asset Type', type: 'select', required: true,
      options: ['Banner', 'Logo', 'Icon', 'Print', 'Digital', 'Listing Image', 'Packaging', 'Other'] },
    { key: 'dimensions', label: 'Dimensions / Specs', type: 'text', required: true },
    { key: 'copy_provided', label: 'Copy Provided?', type: 'yesno', required: true },
    { key: 'copy_text', label: 'Copy Text', type: 'textarea', required: false,
      placeholder: 'Paste copy here if provided', conditional: { key: 'copy_provided', value: 'yes' } },
    { key: 'brand_guidelines', label: 'Brand Guidelines Link', type: 'text', required: false },
    { key: 'intended_use', label: 'Intended Use / Placement', type: 'text', required: true,
      placeholder: 'e.g. Amazon listing, website hero, print flyer' },
    { key: 'file_formats', label: 'File Format Required', type: 'multiselect', required: true,
      options: ['PNG', 'PDF', 'SVG', 'AI', 'JPG', 'MP4', 'Other'] },
    { key: 'reference', label: 'Reference / Inspiration', type: 'text', required: false },
    { key: 'deadline', label: 'Deadline', type: 'date', required: true },
  ],

  copy: [
    { key: 'content_type', label: 'Content Type', type: 'select', required: true,
      options: ['Blog', 'Email', 'Website', 'Script', 'Social Caption', 'Press Release', 'Product Description', 'Other'] },
    { key: 'word_count', label: 'Approximate Word Count', type: 'text', required: true,
      placeholder: 'e.g. 500 words' },
    { key: 'tone', label: 'Tone / Voice', type: 'text', required: true,
      placeholder: 'e.g. Energetic, Professional, Playful' },
    { key: 'audience', label: 'Target Audience', type: 'text', required: true },
    { key: 'placement', label: 'Where It Will Live', type: 'text', required: true,
      placeholder: 'e.g. Website homepage, email newsletter' },
    { key: 'key_messages', label: 'Key Messages', type: 'textarea', required: true,
      placeholder: 'What must the copy communicate?' },
    { key: 'reference_links', label: 'Reference Links', type: 'text', required: false },
    { key: 'deadline', label: 'Deadline', type: 'date', required: true },
  ],

  photo_video: [
    { key: 'shoot_type', label: 'Shoot Type', type: 'select', required: true,
      options: ['Product', 'Lifestyle', 'Event', 'Documentary', 'Interview', 'Unboxing', 'Other'] },
    { key: 'location', label: 'Location', type: 'text', required: true,
      placeholder: 'Studio / on-location address / virtual' },
    { key: 'talent_needed', label: 'Talent / Subjects Required?', type: 'yesno', required: true },
    { key: 'talent_details', label: 'Talent Details', type: 'text', required: false,
      placeholder: 'Describe talent or subjects needed',
      conditional: { key: 'talent_needed', value: 'yes' } },
    { key: 'usage_rights', label: 'Usage Rights', type: 'select', required: true,
      options: ['Internal Only', 'External / Organic', 'Paid Media', 'All Rights'] },
    { key: 'delivery_formats', label: 'Delivery Format', type: 'multiselect', required: true,
      options: ['RAW', 'JPEG', 'MP4', 'MOV', 'GIF', 'Other'] },
    { key: 'shoot_date', label: 'Desired Shoot Date', type: 'date', required: true },
    { key: 'brief', label: 'Brief / Shot List', type: 'textarea', required: false },
    { key: 'reference', label: 'Reference / Mood', type: 'text', required: false },
  ],

  '3d': [
    { key: 'project_type', label: 'Project Type', type: 'select', required: true,
      options: ['Product Render', 'Animation', 'Motion Graphics', 'Environment', 'Explainer', 'Other'] },
    { key: 'reference_visuals', label: 'Reference Visuals', type: 'text', required: true,
      placeholder: 'Link to references or describe the look' },
    { key: 'file_formats', label: 'File Format Required', type: 'multiselect', required: true,
      options: ['MP4', 'MOV', 'GIF', 'PNG Sequence', 'GLB', 'FBX', 'Other'] },
    { key: 'render_quality', label: 'Render Quality', type: 'select', required: true,
      options: ['Draft', 'Standard', 'High', 'Hero'] },
    { key: 'animation_needed', label: 'Animation Required?', type: 'yesno', required: true },
    { key: 'duration', label: 'Duration (seconds)', type: 'text', required: false,
      placeholder: 'e.g. 15',
      conditional: { key: 'animation_needed', value: 'yes' } },
    { key: 'deadline', label: 'Deadline', type: 'date', required: true },
    { key: 'notes', label: 'Additional Notes', type: 'textarea', required: false },
  ],

  deck: [
    { key: 'purpose', label: 'Purpose / Occasion', type: 'text', required: true,
      placeholder: 'e.g. Investor pitch, sales presentation, brand overview' },
    { key: 'audience', label: 'Audience', type: 'text', required: true },
    { key: 'slide_count', label: 'Estimated Slide Count', type: 'text', required: true,
      placeholder: 'e.g. 15 slides' },
    { key: 'copy_provided', label: 'Copy Provided?', type: 'yesno', required: true },
    { key: 'data_provided', label: 'Data / Charts Provided?', type: 'yesno', required: true },
    { key: 'template', label: 'Template to Use', type: 'select', required: true,
      options: ['Standard Brand Template', 'Investor Template', 'Sales Template', 'Custom'] },
    { key: 'deadline', label: 'Deadline', type: 'date', required: true },
    { key: 'reference', label: 'Reference Decks', type: 'text', required: false,
      placeholder: 'Link to reference or inspiration decks' },
  ],

  ad: [
    { key: 'platforms', label: 'Platform(s)', type: 'multiselect', required: true,
      options: ['Meta', 'Google', 'TikTok', 'LinkedIn', 'YouTube', 'OOH', 'Print', 'Other'] },
    { key: 'ad_format', label: 'Ad Format', type: 'select', required: true,
      options: ['Static Image', 'Carousel', 'Video', 'Story / Reel', 'Display Banner', 'Other'] },
    { key: 'sizes', label: 'Sizes Required', type: 'text', required: true,
      placeholder: 'e.g. 1080×1080, 1200×628, 9:16' },
    { key: 'copy_provided', label: 'Copy Provided?', type: 'yesno', required: true },
    { key: 'copy_text', label: 'Copy / Headlines', type: 'textarea', required: false,
      conditional: { key: 'copy_provided', value: 'yes' } },
    { key: 'cta', label: 'Call to Action', type: 'text', required: true,
      placeholder: 'e.g. Shop Now, Learn More' },
    { key: 'campaign_link', label: 'Campaign Link', type: 'text', required: false },
    { key: 'go_live_date', label: 'Go-Live Date', type: 'date', required: true },
    { key: 'reference', label: 'Reference / Examples', type: 'text', required: false },
  ],

};
