// Damage / scrap / return-to-vendor manifest. Renders a printable HTML
// document listing every line in a batch with totals + signature area.
// Used for /damage-ledger batch actions and reprints.
//
// header: {
//   batch_no, batch_type ('REPAIR' | 'SCRAP' | 'RTV'),
//   destination, created_at, prepared_by_name, total_items, total_qty
// }
// rows: damage_ledger rows with ledger_no, part_code, part_name, qty,
//       source, source_ref, reason
export function buildDamageManifestHtml(header, rows) {
  const h = header || {};
  const title = h.batch_type === 'SCRAP'
    ? 'SCRAP DISPOSAL MANIFEST'
    : h.batch_type === 'RTV'
      ? 'RETURN TO VENDOR MANIFEST'
      : 'DAMAGE REPAIR MANIFEST';
  const destLabel = h.batch_type === 'SCRAP'
    ? 'Disposal Method'
    : h.batch_type === 'RTV'
      ? 'Vendor'
      : 'Repair Destination';
  const dateStr = h.created_at
    ? new Date(h.created_at).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
    : '';
  const totalQty = rows.reduce((s, r) => s + (parseInt(r.qty) || 0), 0);
  const tableRows = rows.map((r, i) => `
    <tr>
      <td class="num">${i + 1}</td>
      <td class="mono">${r.ledger_no || ''}</td>
      <td class="mono">${r.part_code || ''}</td>
      <td>${r.part_name || ''}</td>
      <td class="num mono"><strong>${r.qty || 0}</strong></td>
      <td class="mono small">${(r.source || '').replace(/_/g, ' ')}</td>
      <td class="mono small">${r.source_ref || ''}</td>
      <td class="small">${r.reason || ''}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html><head><title>${title} — ${h.batch_no || ''}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, sans-serif; padding: 18mm; color: #000; font-size: 11pt; }
  .ttl { text-align: center; font-size: 14pt; font-weight: 900; letter-spacing: 0.15em; border-bottom: 2px solid #000; padding-bottom: 6px; margin-bottom: 14px; }
  .hdr { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; margin-bottom: 16px; font-size: 10.5pt; }
  .hdr .k { color: #555; font-size: 9pt; letter-spacing: 0.05em; text-transform: uppercase; }
  .hdr .v { font-weight: 700; margin-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 14px; font-size: 9.5pt; }
  th { background: #eee; padding: 5px 6px; text-align: left; border-bottom: 1.5px solid #000; font-size: 8pt; letter-spacing: 0.04em; text-transform: uppercase; }
  td { padding: 4px 6px; border-bottom: 1px solid #ccc; vertical-align: top; }
  td.num { text-align: right; }
  td.mono { font-family: 'Courier New', monospace; }
  td.small { font-size: 8.5pt; color: #444; }
  tfoot td { border-top: 1.5px solid #000; font-weight: 800; padding-top: 6px; }
  .sig { margin-top: 32px; display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 32px; }
  .sigbox { border-top: 1px solid #000; padding-top: 4px; text-align: center; font-size: 9pt; color: #555; text-transform: uppercase; letter-spacing: 0.05em; }
  .meta { margin-top: 14px; font-size: 8.5pt; color: #666; text-align: center; }
  @media print { body { padding: 12mm; } }
</style></head>
<body>
  <div class="ttl">${title}</div>

  <div class="hdr">
    <div>
      <div class="k">Batch No</div>
      <div class="v" style="font-family:'Courier New',monospace;font-size:13pt">${h.batch_no || '—'}</div>
    </div>
    <div>
      <div class="k">${destLabel}</div>
      <div class="v">${h.destination || '—'}</div>
    </div>
    <div>
      <div class="k">Prepared</div>
      <div class="v">${dateStr || '—'}</div>
    </div>
    <div>
      <div class="k">Prepared By</div>
      <div class="v">${h.prepared_by_name || '—'}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:32px">#</th>
        <th>Ledger</th>
        <th>Part Code</th>
        <th>Part Name</th>
        <th style="text-align:right">Qty</th>
        <th>Source</th>
        <th>Ref</th>
        <th>Reason</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="4" style="text-align:right">TOTAL</td>
        <td class="num mono">${totalQty}</td>
        <td colspan="3"></td>
      </tr>
    </tfoot>
  </table>

  <div class="sig">
    <div class="sigbox">Prepared By<br/><span style="opacity:0">.</span></div>
    <div class="sigbox">Verified By<br/><span style="opacity:0">.</span></div>
    <div class="sigbox">Received / Disposed By<br/><span style="opacity:0">.</span></div>
  </div>

  <div class="meta">${rows.length} item${rows.length === 1 ? '' : 's'} · Generated by Legend of Toys Garage</div>
</body></html>`;
}
